from app.models.source import SourceType

SOURCES: list[dict] = [
    {
        "id": "astronomy_com_news",
        "name": "Astronomy.com News",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/news/",
        "feed_url": "https://www.astronomy.com/feed/",
        "country": "USA",
        "category": ["news", "general"],
    },
    {
        "id": "astronomy_com_solar_system",
        "name": "Astronomy.com Solar System",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/solar-system/",
        "feed_url": "https://www.astronomy.com/science/solar-system/feed/",
        "country": "USA",
        "category": ["solar-system", "planets"],
    },
    {
        "id": "astronomy_com_exoplanets",
        "name": "Astronomy.com Exoplanets",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/exoplanets/",
        "feed_url": "https://www.astronomy.com/science/exoplanets/feed/",
        "country": "USA",
        "category": ["exoplanets"],
    },
    {
        "id": "astronomy_com_stars",
        "name": "Astronomy.com Stars",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/stars/",
        "feed_url": "https://www.astronomy.com/science/stars/feed/",
        "country": "USA",
        "category": ["stars"],
    },
    {
        "id": "astronomy_com_milky_way",
        "name": "Astronomy.com Milky Way",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/milky-way/",
        "feed_url": "https://www.astronomy.com/science/milky-way/feed/",
        "country": "USA",
        "category": ["milky-way", "galaxies"],
    },
    {
        "id": "astronomy_com_galaxies",
        "name": "Astronomy.com Galaxies",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/galaxies/",
        "feed_url": "https://www.astronomy.com/science/galaxies/feed/",
        "country": "USA",
        "category": ["galaxies"],
    },
    {
        "id": "astronomy_com_exotic_objects",
        "name": "Astronomy.com Exotic Objects",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/exotic-objects/",
        "feed_url": "https://www.astronomy.com/science/exotic-objects/feed/",
        "country": "USA",
        "category": ["exotic-objects", "black-holes", "cosmology"],
    },
    {
        "id": "astronomy_com_cosmology",
        "name": "Astronomy.com Cosmology",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/cosmology/",
        "feed_url": "https://www.astronomy.com/science/cosmology/feed/",
        "country": "USA",
        "category": ["cosmology", "universe"],
    },
    {
        "id": "astronomy_com_this_week",
        "name": "Astronomy.com This Week in Astronomy",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/tags/this-week-in-astronomy/",
        "feed_url": "https://www.astronomy.com/tags/this-week-in-astronomy/feed/",
        "country": "USA",
        "category": ["this-week-in-astronomy", "observing"],
    },
    {
        "id": "astronomy_com_history",
        "name": "Today in the History of Astronomy",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/today-in-the-history-of-astronomy/",
        "feed_url": "https://www.astronomy.com/today-in-the-history-of-astronomy/feed/",
        "country": "USA",
        "category": ["today-in-the-history-of-astronomy", "history"],
    },
    {
        "id": "astronomy_com_launches",
        "name": "What's Launching This Week",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/whats-launching-this-week/",
        "feed_url": "https://www.astronomy.com/whats-launching-this-week/feed/",
        "country": "USA",
        "category": ["launches", "rockets"],
    },
    {
        "id": "astronomy_com_human_spaceflight",
        "name": "Human Spaceflight",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/space-exploration/human-spaceflight/",
        "feed_url": "https://www.astronomy.com/space-exploration/human-spaceflight/feed/",
        "country": "USA",
        "category": ["human-spaceflight", "spaceflight", "artemis"],
    },
    {
        "id": "astronomy_com_robotic_spaceflight",
        "name": "Robotic Spaceflight",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/space-exploration/robotic-spaceflight/",
        "feed_url": "https://www.astronomy.com/space-exploration/robotic-spaceflight/feed/",
        "country": "USA",
        "category": ["robotic-spaceflight", "spaceflight", "probes"],
    },
    {
        "id": "universetoday",
        "name": "Universe Today",
        "type": SourceType.RSS,
        "url": "https://www.universetoday.com/",
        "feed_url": "https://www.universetoday.com/feed",
        "country": "USA",
        "category": ["news", "space", "cosmology"],
    },
    {
        "id": "space_com",
        "name": "Space.com",
        "type": SourceType.RSS,
        "url": "https://www.space.com/astronomy",
        "feed_url": "https://www.space.com/feeds/all",
        "country": "USA",
        "category": ["news", "astronomy", "spaceflight"],
    },
    # ─── Institutional & Research Centers ──────────────────────────────────────────
    {
        "id": "mit_astrophysics",
        "name": "MIT News — Astrophysics",
        "type": SourceType.RSS,
        "url": "https://news.mit.edu/topic/astrophysics",
        "feed_url": "https://news.mit.edu/rss/topic/astrophysics",
        "country": "USA",
        "category": ["astrophysics", "research", "cosmology", "physics"],
    },
    {
        "id": "nature_astronomy",
        "name": "Nature — Astronomy & Astrophysics",
        "type": SourceType.RSS,
        "url": "https://www.nature.com/subjects/astronomy-and-astrophysics",
        "feed_url": "https://www.nature.com/subjects/astronomy-and-astrophysics.rss",
        "country": "International",
        "category": ["research", "astrophysics", "cosmology", "peer-reviewed"],
    },
    {
        "id": "nature_cosmology",
        "name": "Nature — Cosmology",
        "type": SourceType.RSS,
        "url": "https://www.nature.com/subjects/cosmology",
        "feed_url": "https://www.nature.com/subjects/cosmology.rss",
        "country": "International",
        "category": ["cosmology", "research", "dark-energy", "early-universe"],
    },
    {
        "id": "harvard_cfa",
        "name": "Harvard-Smithsonian Center for Astrophysics",
        "type": SourceType.RSS,
        "url": "https://www.cfa.harvard.edu/news",
        "feed_url": "https://www.cfa.harvard.edu/rss.xml",
        "country": "USA",
        "category": ["astrophysics", "observatory", "research", "telescopes"],
    },
    {
        "id": "nasa_gsfc_astrophysics",
        "name": "NASA Goddard Space Flight Center — Astrophysics",
        "type": SourceType.RSS,
        "url": "https://science.gsfc.nasa.gov/astrophysics/pressreleases/",
        "feed_url": "https://www.nasa.gov/rss/dyn/breaking_news.rss",
        "country": "USA",
        "category": ["nasa", "astrophysics", "spaceflight", "missions"],
    },
    {
        "id": "mpa_garching",
        "name": "Max Planck Institute for Astrophysics",
        "type": SourceType.RSS,
        "url": "https://www.mpa-garching.mpg.de/92335/All_News",
        "feed_url": "https://www.mpa-garching.mpg.de/rss",
        "country": "Germany",
        "category": ["astrophysics", "cosmology", "theoretical-physics", "research"],
    },
    {
        "id": "quanta_cosmology",
        "name": "Quanta Magazine — Cosmology",
        "type": SourceType.RSS,
        "url": "https://www.quantamagazine.org/tag/cosmology/",
        "feed_url": "https://www.quantamagazine.org/tag/cosmology/feed/",
        "country": "USA",
        "category": ["cosmology", "fundamental-physics", "quantum-gravity", "universe"],
    },
    {
        "id": "cambridge_cosmology",
        "name": "University of Cambridge — Cosmology & Astrophysics",
        "type": SourceType.RSS,
        "url": "https://www.cam.ac.uk/subjects/cosmology",
        "feed_url": "https://www.cam.ac.uk/research/feed",
        "country": "UK",
        "category": ["cosmology", "research", "academic", "theoretical-physics"],
    },
    {
        "id": "sciam_cosmology",
        "name": "Scientific American — Cosmology & Space",
        "type": SourceType.RSS,
        "url": "https://www.scientificamerican.com/cosmology/",
        "feed_url": "https://rss.sciam.com/ScientificAmerican-Global",
        "country": "USA",
        "category": ["cosmology", "space-science", "astronomy-news"],
    },
    {
        "id": "sky_telescope_cosmology",
        "name": "Sky & Telescope — Cosmology",
        "type": SourceType.RSS,
        "url": "https://skyandtelescope.org/astronomy-news/cosmology/",
        "feed_url": "https://skyandtelescope.org/astronomy-news/cosmology/feed/",
        "country": "USA",
        "category": ["cosmology", "universe", "astronomy-news"],
    },
    {
        "id": "sky_telescope_black_holes",
        "name": "Sky & Telescope — Black Holes",
        "type": SourceType.RSS,
        "url": "https://skyandtelescope.org/astronomy-news/black-holes/",
        "feed_url": "https://skyandtelescope.org/astronomy-news/black-holes/feed/",
        "country": "USA",
        "category": ["black-holes", "exotic-objects", "astrophysics", "astronomy-news"],
    },
    {
        "id": "sky_telescope_spacecraft",
        "name": "Sky & Telescope — Spacecraft & Space Missions",
        "type": SourceType.RSS,
        "url": "https://skyandtelescope.org/astronomy-news/spacecraft-and-space-missions/",
        "feed_url": "https://skyandtelescope.org/astronomy-news/spacecraft-and-space-missions/feed/",
        "country": "USA",
        "category": ["spacecraft", "missions", "probes", "spaceflight"],
    },
    {
        "id": "sky_telescope_observing",
        "name": "Sky & Telescope — Observing News",
        "type": SourceType.RSS,
        "url": "https://skyandtelescope.org/astronomy-news/observing-news/",
        "feed_url": "https://skyandtelescope.org/astronomy-news/observing-news/feed/",
        "country": "USA",
        "category": ["observing", "amateur-astronomy", "sky-events", "stargazing"],
    },
]
