from app.models.source import SourceType

SOURCES: list[dict] = [
    {
        "id": "astronomy_com_news",
        "name": "Astronomy.com News",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/news/",
        "feed_url": "https://www.astronomy.com/feed/",
        "country": "USA",
        "category": ["news", "general"],
    },
    {
        "id": "astronomy_com_solar_system",
        "name": "Astronomy.com Solar System",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/solar-system/",
        "feed_url": "https://www.astronomy.com/science/solar-system/feed/",
        "country": "USA",
        "category": ["solar-system", "planets"],
    },
    {
        "id": "astronomy_com_exoplanets",
        "name": "Astronomy.com Exoplanets",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/exoplanets/",
        "feed_url": "https://www.astronomy.com/science/exoplanets/feed/",
        "country": "USA",
        "category": ["exoplanets"],
    },
    {
        "id": "astronomy_com_stars",
        "name": "Astronomy.com Stars",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/stars/",
        "feed_url": "https://www.astronomy.com/science/stars/feed/",
        "country": "USA",
        "category": ["stars"],
    },
    {
        "id": "astronomy_com_milky_way",
        "name": "Astronomy.com Milky Way",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/milky-way/",
        "feed_url": "https://www.astronomy.com/science/milky-way/feed/",
        "country": "USA",
        "category": ["milky-way", "galaxies"],
    },
    {
        "id": "astronomy_com_galaxies",
        "name": "Astronomy.com Galaxies",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/galaxies/",
        "feed_url": "https://www.astronomy.com/science/galaxies/feed/",
        "country": "USA",
        "category": ["galaxies"],
    },
    {
        "id": "astronomy_com_exotic_objects",
        "name": "Astronomy.com Exotic Objects",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/exotic-objects/",
        "feed_url": "https://www.astronomy.com/science/exotic-objects/feed/",
        "country": "USA",
        "category": ["exotic-objects", "black-holes", "cosmology"],
    },
    {
        "id": "astronomy_com_cosmology",
        "name": "Astronomy.com Cosmology",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/science/cosmology/",
        "feed_url": "https://www.astronomy.com/science/cosmology/feed/",
        "country": "USA",
        "category": ["cosmology", "universe"],
    },
    {
        "id": "astronomy_com_this_week",
        "name": "Astronomy.com This Week in Astronomy",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/tags/this-week-in-astronomy/",
        "feed_url": "https://www.astronomy.com/tags/this-week-in-astronomy/feed/",
        "country": "USA",
        "category": ["this-week-in-astronomy", "observing"],
    },
    {
        "id": "astronomy_com_history",
        "name": "Today in the History of Astronomy",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/today-in-the-history-of-astronomy/",
        "feed_url": "https://www.astronomy.com/today-in-the-history-of-astronomy/feed/",
        "country": "USA",
        "category": ["today-in-the-history-of-astronomy", "history"],
    },
    {
        "id": "astronomy_com_launches",
        "name": "What's Launching This Week",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/whats-launching-this-week/",
        "feed_url": "https://www.astronomy.com/whats-launching-this-week/feed/",
        "country": "USA",
        "category": ["launches", "rockets"],
    },
    {
        "id": "astronomy_com_human_spaceflight",
        "name": "Human Spaceflight",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/space-exploration/human-spaceflight/",
        "feed_url": "https://www.astronomy.com/space-exploration/human-spaceflight/feed/",
        "country": "USA",
        "category": ["human-spaceflight", "spaceflight", "artemis"],
    },
    {
        "id": "astronomy_com_robotic_spaceflight",
        "name": "Robotic Spaceflight",
        "type": SourceType.RSS,
        "url": "https://www.astronomy.com/space-exploration/robotic-spaceflight/",
        "feed_url": "https://www.astronomy.com/space-exploration/robotic-spaceflight/feed/",
        "country": "USA",
        "category": ["robotic-spaceflight", "spaceflight", "probes"],
    },
    {
        "id": "universetoday",
        "name": "Universe Today",
        "type": SourceType.RSS,
        "url": "https://www.universetoday.com/",
        "feed_url": "https://www.universetoday.com/feed",
        "country": "USA",
        "category": ["news", "space", "cosmology"],
    },
    {
        "id": "space_com",
        "name": "Space.com",
        "type": SourceType.RSS,
        "url": "https://www.space.com/astronomy",
        "feed_url": "https://www.space.com/feeds/all",
        "country": "USA",
        "category": ["news", "astronomy", "spaceflight"],
    },
]

