export type Region =
  | 'Africa'
  | 'North & Central America'
  | 'South America'
  | 'Europe'
  | 'Middle East'
  | 'Asia'
  | 'Oceania'
  | 'International Bodies'

export interface SpaceAgency {
  slug: string
  acronym: string
  name: string
  country: string
  region: Region
  flag: string
  headquarters?: string
  established?: string
  website?: string
  description: string
  searchTerms: string[]
  keyMissions?: string[]
}

export const SPACE_AGENCIES: SpaceAgency[] = [
  // =========================================================================
  // AFRICA
  // =========================================================================
  {
    slug: 'asal-algeria',
    acronym: 'ASAL',
    name: 'Algerian Space Agency (Agence Spatiale Algérienne)',
    country: 'Algeria',
    region: 'Africa',
    flag: '🇩🇿',
    headquarters: 'Algiers, Algeria',
    established: '2002',
    website: 'https://www.asal.dz',
    description:
      'Algeria’s government space agency directing national space technologies, the Alsat high-resolution Earth observation constellation (Alsat-1B, Alsat-2A/B), and the Alcomsat-1 geostationary telecommunications satellite.',
    searchTerms: ['Algerian Space Agency', 'ASAL', 'Algeria space', 'Alsat', 'Alcomsat-1'],
    keyMissions: ['Alsat-2 Optical Earth Observation Constellation', 'Alcomsat-1 Telecom', 'National Space Program 2040'],
  },
  {
    slug: 'ggpen-angola',
    acronym: 'GGPEN',
    name: 'National Space Program Management Office (Gabinete de Gestão do Programa Espacial Nacional)',
    country: 'Angola',
    region: 'Africa',
    flag: '🇦🇴',
    headquarters: 'Luanda, Angola',
    established: '2013',
    website: 'https://ggpen.gov.ao',
    description:
      'Angola’s national space management office responsible for the AngoSat satellite telecommunications program (AngoSat-2 launched in 2022), Earth observation applications, and space science education across Southern Africa.',
    searchTerms: ['GGPEN', 'Angola space', 'AngoSat-2', 'AngoSat', 'Luanda space'],
    keyMissions: ['AngoSat-2 High-Throughput Communications Satellite', 'National Earth Observation Applications', 'Space Education Program'],
  },
  {
    slug: 'egsa',
    acronym: 'EgSA',
    name: 'Egyptian Space Agency',
    country: 'Egypt',
    region: 'Africa',
    flag: '🇪🇬',
    headquarters: 'Space City, New Administrative Capital, Cairo, Egypt',
    established: '2018',
    website: 'https://egsa.gov.eg',
    description:
      'Egypt’s national space authority and host of the African Space Agency (AfSA) headquarters in Space City, operating MisrSat-2, EgyptSat-A, and the African Development Satellite constellation.',
    searchTerms: ['Egyptian Space Agency', 'EgSA', 'Egypt space', 'MisrSat-2', 'AfSA Cairo', 'EgyptSat'],
    keyMissions: ['MisrSat-2 High-Resolution Imaging Satellite', 'African Space Agency (AfSA) Continental HQ', 'NExSat-1 Tech Demonstrator'],
  },
  {
    slug: 'esti-ethiopia',
    acronym: 'SSGI / ESTI',
    name: 'Space Science and Geospatial Institute (formerly ESTI)',
    country: 'Ethiopia',
    region: 'Africa',
    flag: '🇪🇹',
    headquarters: 'Addis Ababa, Ethiopia',
    established: '2016',
    website: 'https://ssgi.gov.et',
    description:
      'Ethiopia’s principal space science and geospatial institute managing the ETRSS-1 remote sensing satellite, Entoto Astronomical Observatory, and aerospace engineering in the Horn of Africa.',
    searchTerms: ['Space Science and Geospatial Institute', 'ESTI', 'SSGI', 'Ethiopia space', 'ETRSS-1', 'Entoto Observatory'],
    keyMissions: ['ETRSS-1 Remote Sensing Satellite', 'Entoto Astronomical Observatory', 'East African Geospatial Data Center'],
  },
  {
    slug: 'ksa-kenya',
    acronym: 'KSA / KENSA',
    name: 'Kenya Space Agency',
    country: 'Kenya',
    region: 'Africa',
    flag: '🇰🇪',
    headquarters: 'Nairobi, Kenya',
    established: '2017',
    website: 'https://ksa.go.ke',
    description:
      'Coordinates Kenyan space activities, the historic Luigi Broglio Space Center (San Marco equatorial platform in Malindi), and the Taifa-1 operational optical Earth observation satellite.',
    searchTerms: ['Kenya Space Agency', 'KSA Kenya', 'KENSA', 'Taifa-1', 'Malindi spaceport', 'San Marco platform'],
    keyMissions: ['Taifa-1 Optical Earth Observation Satellite', 'Luigi Broglio Space Center (Malindi)', 'Strategic Space Plan 2030'],
  },
  {
    slug: 'crts-morocco',
    acronym: 'CRTS',
    name: 'Royal Centre for Remote Sensing (Centre Royal de Télédétection Spatiale)',
    country: 'Morocco',
    region: 'Africa',
    flag: '🇲🇦',
    headquarters: 'Rabat, Morocco',
    established: '1989',
    website: 'http://www.crts.gov.ma',
    description:
      'Morocco’s national remote sensing authority managing the Mohammed VI-A and Mohammed VI-B high-resolution optical Earth reconnaissance satellite constellation and national space cartography.',
    searchTerms: ['Royal Centre for Remote Sensing', 'CRTS', 'Morocco space', 'Mohammed VI satellite', 'Rabat space'],
    keyMissions: ['Mohammed VI-A & VI-B Reconnaissance Constellation', 'Mediterranean & Saharan Remote Sensing', 'Space Spatial Data Infrastructure'],
  },
  {
    slug: 'nasrda',
    acronym: 'NASRDA',
    name: 'National Space Research and Development Agency',
    country: 'Nigeria',
    region: 'Africa',
    flag: '🇳🇬',
    headquarters: 'Abuja, Nigeria',
    established: '1999',
    website: 'https://nasrda.gov.ng',
    description:
      'Nigeria’s primary government space agency operating NigeriaSat Earth observation satellites and NigComSat communications satellites, advancing food security, mineral surveying, and aerospace engineering.',
    searchTerms: ['NASRDA', 'Nigeria space', 'NigeriaSat', 'NigComSat', 'Abuja space agency'],
    keyMissions: ['NigeriaSat-2 & NigeriaSat-X Remote Sensing', 'NigComSat-1R Telecom Satellite', 'Centre for Satellite Technology Development'],
  },
  {
    slug: 'rsa-rwanda',
    acronym: 'RSA',
    name: 'Rwanda Space Agency',
    country: 'Rwanda',
    region: 'Africa',
    flag: '🇷🇼',
    headquarters: 'Kigali, Rwanda',
    established: '2021',
    website: 'https://space.gov.rw',
    description:
      'Africa’s fast-rising space authority pioneering satellite mega-constellation filings (Cinnamon), national geospatial analytics via GeoHub, and Artemis Accords international collaboration.',
    searchTerms: ['Rwanda Space Agency', 'RSA Rwanda', 'Rwanda space', 'Rwasat-1', 'Kigali space', 'Cinnamon constellation'],
    keyMissions: ['National GeoHub Analytics Platform', 'Artemis Accords African Signatory', 'RwaSat Micro-satellite Constellation'],
  },
  {
    slug: 'sansa',
    acronym: 'SANSA',
    name: 'South African National Space Agency',
    country: 'South Africa',
    region: 'Africa',
    flag: '🇿🇦',
    headquarters: 'Pretoria & Hermanus, South Africa',
    established: '2010',
    website: 'https://www.sansa.org.za',
    description:
      'South Africa’s space agency managing the Hermanus Space Weather Regional Warning Centre, deep-space telemetry at Hartebeesthoek (ground tracking for NASA Artemis), and Earth observation satellites.',
    searchTerms: ['South African National Space Agency', 'SANSA', 'South Africa space', 'Hartebeesthoek', 'Space Weather Hermanus'],
    keyMissions: ['Deep Space Ground Tracking for Artemis', 'Hermanus Space Weather Warning Centre', 'ZACube CubeSat Series', 'Space Infrastructure Hub'],
  },
  {
    slug: 'cnct-tunisia',
    acronym: 'CNCT',
    name: 'National Remote Sensing Center (Centre National de la Cartographie et de la Télédétection)',
    country: 'Tunisia',
    region: 'Africa',
    flag: '🇹🇳',
    headquarters: 'Tunis, Tunisia',
    established: '1988',
    website: 'http://www.cnct.nat.tn',
    description:
      'Tunisia’s national authority for space cartography and remote sensing, collaborating with domestic tech innovators behind the Challenge-One satellite and IoT constellation initiatives.',
    searchTerms: ['CNCT', 'Tunisia space', 'Challenge-One', 'Tunis remote sensing'],
    keyMissions: ['Challenge-One IoT Satellite Integration', 'National Space Cartography & Geographic Information System'],
  },
  {
    slug: 'zingsa-zimbabwe',
    acronym: 'ZINGSA',
    name: 'Zimbabwe National Geospatial and Space Agency',
    country: 'Zimbabwe',
    region: 'Africa',
    flag: '🇿🇼',
    headquarters: 'Harare, Zimbabwe',
    established: '2018',
    website: 'https://zingsa.ac.zw',
    description:
      'Zimbabwe’s space and geospatial agency driving the ZimSat-1 Earth observation cubesat mission deployed from the ISS, drone mapping, and agricultural forecasting.',
    searchTerms: ['ZINGSA', 'Zimbabwe space', 'ZIMSAT-1', 'Harare space agency'],
    keyMissions: ['ZimSat-1 Earth Observation CubeSat', 'National Geospatial Intelligence Center', 'Agricultural Drought Early Warning'],
  },

  // =========================================================================
  // NORTH & CENTRAL AMERICA
  // =========================================================================
  {
    slug: 'nasa',
    acronym: 'NASA',
    name: 'National Aeronautics and Space Administration',
    country: 'United States',
    region: 'North & Central America',
    flag: '🇺🇸',
    headquarters: 'Washington, D.C., USA',
    established: '1958',
    website: 'https://www.nasa.gov',
    description:
      'The civilian space agency of the United States government responsible for the civilian space program, aeronautics research, and space exploration including the Artemis lunar campaign, James Webb Space Telescope, and Mars exploration rovers.',
    searchTerms: ['NASA', 'Artemis', 'Perseverance', 'Curiosity', 'James Webb', 'JWST', 'Hubble', 'Kennedy Space Center', 'JPL', 'Goddard'],
    keyMissions: ['Artemis Program', 'James Webb Space Telescope', 'Perseverance Mars Rover', 'Europa Clipper', 'Commercial Crew'],
  },
  {
    slug: 'csa-asc',
    acronym: 'CSA/ASC',
    name: 'Canadian Space Agency / Agence spatiale canadienne',
    country: 'Canada',
    region: 'North & Central America',
    flag: '🇨🇦',
    headquarters: 'Longueuil, Quebec, Canada',
    established: '1989',
    website: 'https://www.asc-csa.gc.ca',
    description:
      'Canada’s national space agency, leader in advanced space robotics (Canadarm, Canadarm2, Canadarm3), satellite Earth observation (RADARSAT), and astronaut participation in the Artemis and ISS programs.',
    searchTerms: ['Canadian Space Agency', 'CSA', 'Canadarm', 'Jeremy Hansen', 'RADARSAT', 'ASC'],
    keyMissions: ['Canadarm3 (Lunar Gateway)', 'Artemis II (Jeremy Hansen)', 'RADARSAT Constellation', 'NEOSSat'],
  },
  {
    slug: 'aem',
    acronym: 'AEM',
    name: 'Agencia Espacial Mexicana (Mexican Space Agency)',
    country: 'Mexico',
    region: 'North & Central America',
    flag: '🇲🇽',
    headquarters: 'Mexico City, Mexico',
    established: '2010',
    website: 'https://www.gob.mx/aem',
    description:
      'Mexico’s decentralized space agency coordinating national space infrastructure, Earth observation applications, scientific research, and international partnerships in Latin America and the Artemis Accords.',
    searchTerms: ['Agencia Espacial Mexicana', 'AEM', 'Mexico space', 'Colmena', 'AztechSat'],
    keyMissions: ['AztechSat Nano-satellites', 'Colmena Lunar Micro-Robotics', 'Earth Observation Network'],
  },

  // =========================================================================
  // SOUTH AMERICA
  // =========================================================================
  {
    slug: 'conae',
    acronym: 'CONAE',
    name: 'Comisión Nacional de Actividades Espaciales',
    country: 'Argentina',
    region: 'South America',
    flag: '🇦🇷',
    headquarters: 'Buenos Aires, Argentina',
    established: '1991',
    website: 'https://www.argentina.gob.ar/ciencia/conae',
    description:
      'Argentina’s civilian space agency specializing in advanced synthetic aperture radar (SAR) Earth observation satellites (SAOCOM series) and satellite engineering through INVAP.',
    searchTerms: ['CONAE', 'Argentina space', 'SAOCOM', 'Tronador', 'SABIA-Mar'],
    keyMissions: ['SAOCOM 1A/1B Radar Constellation', 'SABIA-Mar Ocean Observation', 'Tronador Rocket Project'],
  },
  {
    slug: 'aeb',
    acronym: 'AEB',
    name: 'Agência Espacial Brasileira (Brazilian Space Agency)',
    country: 'Brazil',
    region: 'South America',
    flag: '🇧🇷',
    headquarters: 'Brasília, Brazil',
    established: '1994',
    website: 'https://www.gov.br/aeb',
    description:
      'The Brazilian Space Agency oversees civil space development, the Alcântara Launch Center near the equator, CBERS Earth observation satellites with China, and Amazon environmental monitoring.',
    searchTerms: ['Agencia Espacial Brasileira', 'AEB', 'Brazil space', 'Alcantara', 'CBERS', 'Amazonia-1'],
    keyMissions: ['Amazonia-1', 'CBERS Satellite Series', 'Alcântara Space Center Spaceport'],
  },
  {
    slug: 'aec-chile',
    acronym: 'AEC / SNSAT',
    name: 'Chilean Space Agency / Sistema Nacional Satelital',
    country: 'Chile',
    region: 'South America',
    flag: '🇨🇱',
    headquarters: 'Santiago, Chile',
    established: '2001',
    website: 'https://www.defensa.cl/espacio',
    description:
      'Chile’s national space coordination entity managing the National Satellite System (SNSAT), high-altitude astronomical observatory hosting in the Atacama Desert, and space technologies.',
    searchTerms: ['AEC', 'Chilean Space Agency', 'SNSAT', 'FASat', 'Chile space'],
    keyMissions: ['National Satellite System (SNSAT)', 'FASat-Delta', 'Atacama Space Observation Support'],
  },
  {
    slug: 'aep-paraguay',
    acronym: 'AEP',
    name: 'Agencia Espacial del Paraguay (Paraguayan Space Agency)',
    country: 'Paraguay',
    region: 'South America',
    flag: '🇵🇾',
    headquarters: 'Asunción, Paraguay',
    established: '2014',
    website: 'https://aep.gov.py',
    description:
      'Paraguay’s national space authority leading the GuaraniSat-1 satellite mission deployed from the ISS for vector-borne disease tracking, space education, and Earth observation.',
    searchTerms: ['AEP', 'Paraguayan Space Agency', 'GuaraniSat-1', 'Paraguay space'],
    keyMissions: ['GuaraniSat-1 Satellite Mission', 'National Space Science Capacity Building', 'Chaco Earth Monitoring'],
  },
  {
    slug: 'conida',
    acronym: 'CONIDA',
    name: 'Comisión Nacional de Investigación y Desarrollo Aeroespacial',
    country: 'Peru',
    region: 'South America',
    flag: '🇵🇪',
    headquarters: 'Lima, Peru',
    established: '1974',
    website: 'https://www.gob.pe/conida',
    description:
      'The Peruvian Space Agency operating the high-resolution PeruSat-1 optical Earth observation satellite and advancing astronomical research at the National Astronomical Observatory.',
    searchTerms: ['CONIDA', 'Peruvian Space Agency', 'PeruSat-1', 'Peru space'],
    keyMissions: ['PeruSat-1 High Resolution Earth Observation', 'National Center for Satellite Operations (CNOIS)'],
  },
  {
    slug: 'abae',
    acronym: 'ABAE',
    name: 'Agencia Bolivariana para Actividades Espaciales',
    country: 'Venezuela',
    region: 'South America',
    flag: '🇻🇪',
    headquarters: 'Caracas, Venezuela',
    established: '2007',
    website: 'http://www.abae.gob.ve',
    description:
      'Venezuela’s national space agency operating communications and remote sensing satellites, including the Venesat-1 (Simón Bolívar) and VRSS satellite programs.',
    searchTerms: ['ABAE', 'Venezuela space', 'Venesat', 'Miranda satellite', 'Sucre satellite'],
    keyMissions: ['VRSS-1 Francisco de Miranda', 'VRSS-2 Antonio José de Sucre', 'VeneSat Telecom'],
  },

  // =========================================================================
  // EUROPE (NATIONAL)
  // =========================================================================
  {
    slug: 'ffg-austria',
    acronym: 'FFG / ALR',
    name: 'Austrian Space Agency (Aeronautics and Space Agency via FFG)',
    country: 'Austria',
    region: 'Europe',
    flag: '🇦🇹',
    headquarters: 'Vienna, Austria',
    established: '1972',
    website: 'https://www.ffg.at/en/space',
    description:
      'Austria’s space agency managing Austrian participation in ESA, satellite communications, the BRITE-Constellation space astronomy mission (BRITE-Austria, UniBRITE), and quantum communications.',
    searchTerms: ['Austrian Space Agency', 'FFG Space', 'Austria space', 'BRITE-Austria', 'UniBRITE'],
    keyMissions: ['BRITE-Constellation Stellar Astronomy', 'Quantum Optical Space Links', 'ESA Science Consortia Contributions'],
  },
  {
    slug: 'azercosmos',
    acronym: 'Azercosmos / MAKA',
    name: 'Space Agency of the Republic of Azerbaijan (Azercosmos)',
    country: 'Azerbaijan',
    region: 'Europe',
    flag: '🇦🇿',
    headquarters: 'Baku, Azerbaijan',
    established: '1992',
    website: 'https://azercosmos.az',
    description:
      'The premier satellite operator and space agency of Azerbaijan, operating Azerspace-1 and Azerspace-2 telecommunications satellites and Azersky Earth observation, and host of IAC 2023 in Baku.',
    searchTerms: ['Azercosmos', 'MAKA', 'Azerbaijan space', 'Azerspace', 'Azersky'],
    keyMissions: ['Azerspace Telecom Fleet', '74th International Astronautical Congress (IAC Baku)', 'Azerbaijan Space Academy'],
  },
  {
    slug: 'belspo-bira',
    acronym: 'BIRA / BELSPO',
    name: 'Belgian Federal Science Policy Office & Royal Belgian Institute for Space Aeronomy',
    country: 'Belgium',
    region: 'Europe',
    flag: '🇧🇪',
    headquarters: 'Brussels, Belgium',
    established: '1959',
    website: 'https://www.aeronomie.be',
    description:
      'Belgium’s space science authorities directing atmospheric aeronomy, the PROBA microsatellite line (PROBA-V, PROBA-3 formation flying coronagraph), and ESA mission payloads.',
    searchTerms: ['BELSPO', 'BIRA-IASB', 'Belgian Space', 'PROBA', 'Belgium space', 'PROBA-3'],
    keyMissions: ['PROBA-3 Solar Coronagraphy Formation Flying', 'ALTIUS Atmospheric Limb Sounder', 'Euro Space Center Research'],
  },
  {
    slug: 'cso',
    acronym: 'CSO',
    name: 'Czech Space Office (Česká kosmická kancelář)',
    country: 'Czech Republic',
    region: 'Europe',
    flag: '🇨🇿',
    headquarters: 'Prague, Czech Republic',
    established: '2003',
    website: 'https://www.czechspaceportal.cz',
    description:
      'Coordinates Czech participation in ESA programs, optical instruments for astronomical satellites, and hosts the EU Agency for the Space Programme (EUSPA) in Prague.',
    searchTerms: ['Czech Space Office', 'CSO', 'Czech space', 'EUSPA Prague', 'VZLUSAT'],
    keyMissions: ['VZLUSAT Technology Demonstrators', 'EUSPA Galileo & Copernicus Coordination', 'ESA Optical Payloads'],
  },
  {
    slug: 'dtu-denmark',
    acronym: 'DTU Space / DASHE',
    name: 'National Space Institute (DTU Space) & Danish Agency for Science and Higher Education',
    country: 'Denmark',
    region: 'Europe',
    flag: '🇩🇰',
    headquarters: 'Lyngby & Copenhagen, Denmark',
    established: '1968',
    website: 'https://www.space.dtu.dk',
    description:
      'Denmark’s national space institute leading magnetic field satellite missions (ESA Swarm), the ASIM atmosphere-space interactions observatory on the ISS, and astrophysics star trackers.',
    searchTerms: ['DTU Space', 'Denmark space', 'ASIM ISS', 'Swarm satellite', 'Danish space'],
    keyMissions: ['ESA Swarm Geomagnetic Constellation', 'ASIM Climate Observatory on ISS', 'DISCO CubeSat Series'],
  },
  {
    slug: 'estcube-estonia',
    acronym: 'Estonian Space Office',
    name: 'Estonian Space Office & Tartu Observatory (ESTCube Program)',
    country: 'Estonia',
    region: 'Europe',
    flag: '🇪🇪',
    headquarters: 'Tallinn & Tartu, Estonia',
    established: '2006',
    website: 'https://www.estcube.eu',
    description:
      'Estonia’s space office and academic program famous for ESTCube-1 (testing the electric solar wind sail) and ESTCube-2, and rapid integration into ESA deep space initiatives.',
    searchTerms: ['ESTCube', 'Estonian Space Office', 'Estonia space', 'Electric solar wind sail', 'Tartu Observatory'],
    keyMissions: ['ESTCube-1 Electric Solar Sail Demonstrator', 'ESTCube-2 In-Orbit Technology Mission', 'ESA Comet Interceptor Optical Camera Support'],
  },
  {
    slug: 'finland-space',
    acronym: 'Finnish Space Agency',
    name: 'Space Finland (Ministry of Economic Affairs and Employment & Business Finland)',
    country: 'Finland',
    region: 'Europe',
    flag: '🇫🇮',
    headquarters: 'Helsinki, Finland',
    established: '2002',
    website: 'https://spacefinland.fi',
    description:
      'Finland’s national space coordinator supporting world-leading radar SAR innovation (ICEYE constellation), Foresail CubeSat missions, and aurora/space weather research.',
    searchTerms: ['Space Finland', 'Finnish Space Agency', 'Finland space', 'ICEYE', 'Foresail', 'Aalto-1'],
    keyMissions: ['ICEYE Commercial Radar SAR Constellation', 'Foresail-1 CubeSat Mission', 'Space Weather & Aurora Instrumentation'],
  },
  {
    slug: 'cnes',
    acronym: 'CNES',
    name: 'Centre National d’Études Spatiales (French Space Agency)',
    country: 'France',
    region: 'Europe',
    flag: '🇫🇷',
    headquarters: 'Paris & Toulouse, France',
    established: '1961',
    website: 'https://cnes.fr',
    description:
      'The French space agency, European leader in launcher development, Guiana Space Centre spaceport operations, climate science, planetary exploration instruments, and satellite innovation.',
    searchTerms: ['CNES', 'France space', 'French space agency', 'Guiana Space Centre', 'Toulouse Space Center', 'SWOT'],
    keyMissions: ['Guiana Space Centre (CSG)', 'SWOT Surface Water and Ocean Topography', 'MicroCarb Climate Mission', 'SuperCam on Perseverance'],
  },
  {
    slug: 'dlr',
    acronym: 'DLR',
    name: 'German Aerospace Center (Deutsches Zentrum für Luft- und Raumfahrt)',
    country: 'Germany',
    region: 'Europe',
    flag: '🇩🇪',
    headquarters: 'Cologne & Oberpfaffenhofen, Germany',
    established: '1969',
    website: 'https://www.dlr.de',
    description:
      'Germany’s national research center for aeronautics and space conducting robotics, planetary exploration, Earth observation (TerraSAR-X, EnMAP), and human spaceflight operations.',
    searchTerms: ['DLR', 'German Aerospace Center', 'Germany space', 'EnMAP', 'TerraSAR-X', 'TanDEM-X'],
    keyMissions: ['Columbus Module Operations', 'EnMAP Hyperspectral Satellite', 'TerraSAR-X Radar', 'MASCOT Asteroid Lander'],
  },
  {
    slug: 'hsa-greece',
    acronym: 'HSA / HSC',
    name: 'Hellenic Space Center / Agency (Ελληνικό Κέντρο Διαστήματος)',
    country: 'Greece',
    region: 'Europe',
    flag: '🇬🇷',
    headquarters: 'Athens, Greece',
    established: '2019',
    website: 'https://hsc.gov.gr',
    description:
      'The Greek national space organization coordinating satellite communications (Hellas Sat), maritime monitoring in the Mediterranean, and national micro-satellite constellations.',
    searchTerms: ['Hellenic Space Center', 'HSA', 'HSC', 'Greece space', 'Hellas Sat', 'Greek space agency'],
    keyMissions: ['National Small Satellite Constellation', 'Hellas Sat Communications', 'Mediterranean Maritime Observation'],
  },
  {
    slug: 'hunor-hungary',
    acronym: 'HUNOR / HSO',
    name: 'Hungarian Space Office (HUNOR – Hungarian to Orbit)',
    country: 'Hungary',
    region: 'Europe',
    flag: '🇭🇺',
    headquarters: 'Budapest, Hungary',
    established: '1992',
    website: 'https://hunor.gov.hu',
    description:
      'Directs Hungary’s national space strategy and the HUNOR astronaut mission to the ISS, space dosimeters (Pille), and academic nanosatellite developments (Masat-1, SMOG-P).',
    searchTerms: ['HUNOR', 'Hungarian Space Office', 'Hungary space', 'Masat-1', 'Pille dosimeter'],
    keyMissions: ['HUNOR Hungarian Astronaut Expedition to ISS', 'SMOG-P PocketQube Electrosmog Satellite', 'Pille Space Radiation Dosimeter'],
  },
  {
    slug: 'ireland-space',
    acronym: 'Enterprise Ireland Space',
    name: 'Enterprise Ireland Space Division & National Space Strategy',
    country: 'Ireland',
    region: 'Europe',
    flag: '🇮🇪',
    headquarters: 'Dublin, Ireland',
    established: '2019',
    website: 'https://www.enterprise-ireland.com/en/space-ireland',
    description:
      'Manages Ireland’s space enterprise ecosystem, ESA programs, and celebrated the launch of EIRSAT-1, Ireland’s very first sovereign orbital satellite.',
    searchTerms: ['Enterprise Ireland Space', 'Ireland space', 'EIRSAT-1', 'Irish space programme'],
    keyMissions: ['EIRSAT-1 Ireland’s First Satellite', 'ESA Space Solutions Centre Ireland', 'Earth Observation Analytics Hub'],
  },
  {
    slug: 'asi',
    acronym: 'ASI',
    name: 'Agenzia Spaziale Italiana (Italian Space Agency)',
    country: 'Italy',
    region: 'Europe',
    flag: '🇮🇹',
    headquarters: 'Rome, Italy',
    established: '1988',
    website: 'https://www.asi.it',
    description:
      'The Italian Space Agency, premier developer of pressurized space station modules (Harmony, Tranquility, Cupola), COSMO-SkyMed radar constellation, Vega rocket architectures, and PRISMA hyperspectral imaging.',
    searchTerms: ['Agenzia Spaziale Italiana', 'ASI', 'Italy space', 'COSMO-SkyMed', 'Vega launcher', 'Prisma'],
    keyMissions: ['COSMO-SkyMed Second Generation Radar', 'Vega Launcher Series', 'PRISMA Hyperspectral Satellite', 'ISS Modules Architecture'],
  },
  {
    slug: 'lsa',
    acronym: 'LSA',
    name: 'Luxembourg Space Agency',
    country: 'Luxembourg',
    region: 'Europe',
    flag: '🇱🇺',
    headquarters: 'Luxembourg City, Luxembourg',
    established: '2018',
    website: 'https://space-agency.public.lu',
    description:
      'World pioneer in commercial space resources legal frameworks, financing newspace ventures, lunar mining ecosystems (SpaceResources.lu), and space communications.',
    searchTerms: ['Luxembourg Space Agency', 'LSA', 'SpaceResources.lu', 'Luxembourg space', 'ESRIC'],
    keyMissions: ['SpaceResources.lu Lunar Mining Initiative', 'European Space Resources Innovation Centre (ESRIC)'],
  },
  {
    slug: 'nso-netherlands',
    acronym: 'NSO / SRON',
    name: 'Netherlands Space Office & SRON Netherlands Institute for Space Research',
    country: 'Netherlands',
    region: 'Europe',
    flag: '🇳🇱',
    headquarters: 'The Hague & Leiden, Netherlands',
    established: '2009',
    website: 'https://www.spaceoffice.nl',
    description:
      'Coordinates Dutch space policy, hosts ESA’s European Space Research and Technology Centre (ESTEC) in Noordwijk, and developed the groundbreaking TROPOMI atmospheric instrument on Sentinel-5P.',
    searchTerms: ['Netherlands Space Office', 'NSO', 'SRON', 'TROPOMI', 'ESTEC Noordwijk', 'Dutch space'],
    keyMissions: ['TROPOMI Air Quality Instrument on Sentinel-5P', 'ESA ESTEC Tech Center Hosting', 'SPEXone Aerosol Polarimeter'],
  },
  {
    slug: 'nosa',
    acronym: 'NOSA',
    name: 'Norwegian Space Agency (Norsk Romsenter)',
    country: 'Norway',
    region: 'Europe',
    flag: '🇳🇴',
    headquarters: 'Oslo, Norway',
    established: '1987',
    website: 'https://www.romsenter.no',
    description:
      'Norway’s government agency managing satellite communications, Arctic maritime surveillance AIS fleets, Andøya Spaceport orbital launch facility, and Svalbard satellite ground stations (SvalSat).',
    searchTerms: ['Norwegian Space Agency', 'NOSA', 'Norsk Romsenter', 'Andøya', 'Norway space', 'SvalSat'],
    keyMissions: ['Andøya Spaceport Orbital Infrastructure', 'Arctic Maritime Surveillance AIS Fleet', 'Svalbard Satellite Ground Station'],
  },
  {
    slug: 'polsa',
    acronym: 'POLSA',
    name: 'Polish Space Agency (Polska Agencja Kosmiczna)',
    country: 'Poland',
    region: 'Europe',
    flag: '🇵🇱',
    headquarters: 'Gdańsk & Warsaw, Poland',
    established: '2014',
    website: 'https://polsa.gov.pl',
    description:
      'Poland’s national space agency supporting Polish space industry integration with ESA, space domain awareness (SDA), Earth observation, and the Artemis Accords.',
    searchTerms: ['Polish Space Agency', 'POLSA', 'Poland space', 'Polska Agencja Kosmiczna'],
    keyMissions: ['Polish Space Surveillance and Tracking (SST)', 'ESA Science Consortia', 'Ignis Micro-Satellite Systems'],
  },
  {
    slug: 'portugal-space',
    acronym: 'PTSPACE',
    name: 'Portuguese Space Agency (Portugal Space)',
    country: 'Portugal',
    region: 'Europe',
    flag: '🇵🇹',
    headquarters: 'Lisbon & Santa Maria (Azores), Portugal',
    established: '2019',
    website: 'https://ptspace.pt',
    description:
      'Develops Portugal’s space strategy, Atlantic Constellation Earth observation satellites, and the Santa Maria spaceport initiative in the Azores.',
    searchTerms: ['Portugal Space', 'PTSPACE', 'Portuguese Space Agency', 'Azores spaceport', 'Atlantic Constellation'],
    keyMissions: ['Atlantic Constellation Earth Observation', 'Santa Maria Azores Space Port Hub', 'Space Rider Landing Site'],
  },
  {
    slug: 'rosa',
    acronym: 'ROSA',
    name: 'Romanian Space Agency (Agenția Spațială Română)',
    country: 'Romania',
    region: 'Europe',
    flag: '🇷🇴',
    headquarters: 'Bucharest, Romania',
    established: '1991',
    website: 'https://www.rosa.ro',
    description:
      'The Romanian Space Agency coordinating national space research, planetary defense participation in ESA’s Hera mission, and space security infrastructure.',
    searchTerms: ['Romanian Space Agency', 'ROSA', 'Romania space', 'Hera mission Romania', 'Goliat'],
    keyMissions: ['ESA Hera Planetary Defense Subsystems', 'Earth Observation Centre', 'Space Situational Awareness'],
  },
  {
    slug: 'roscosmos',
    acronym: 'Roscosmos',
    name: 'State Space Corporation Roscosmos',
    country: 'Russia',
    region: 'Europe',
    flag: '🇷🇺',
    headquarters: 'Moscow, Russia',
    established: '1992',
    website: 'https://www.roscosmos.ru',
    description:
      'The Russian state corporation for space activities operating Soyuz and Progress crew and cargo flights to the ISS, GLONASS navigation constellation, and launch facilities at Baikonur and Vostochny.',
    searchTerms: ['Roscosmos', 'Soyuz', 'Progress', 'Cosmonauts', 'Vostochny', 'GLONASS', 'Baikonur'],
    keyMissions: ['Soyuz Crew Spaceflight', 'ISS Russian Orbital Segment', 'GLONASS Navigation Fleet', 'Luna Exploration'],
  },
  {
    slug: 'aee-spain',
    acronym: 'AEE / CDTI',
    name: 'Agencia Espacial Española (Spanish Space Agency) & CDTI',
    country: 'Spain',
    region: 'Europe',
    flag: '🇪🇸',
    headquarters: 'Seville & Madrid, Spain',
    established: '2023',
    website: 'https://www.aee.gob.es',
    description:
      'Spain’s newly unified national space agency managing the PAZ radar satellite, Ingenio optical systems, PLD Space Miura launch programs, and NASA/ESA Deep Space Communications Complex in Robledo de Chavela.',
    searchTerms: ['Agencia Espacial Espanola', 'AEE', 'Spain space', 'CDTI', 'PAZ satellite', 'Miura rocket', 'Robledo'],
    keyMissions: ['PAZ Synthetic Aperture Radar Satellite', 'Miura Small Satellite Launchers', 'Madrid Deep Space Communications Complex'],
  },
  {
    slug: 'snsa',
    acronym: 'SNSA',
    name: 'Swedish National Space Agency (Rymdstyrelsen)',
    country: 'Sweden',
    region: 'Europe',
    flag: '🇸🇪',
    headquarters: 'Solna, Sweden',
    established: '1972',
    website: 'https://www.rymdstyrelsen.se',
    description:
      'Sweden’s government agency for space activities operating the Esrange Space Center inside the Arctic Circle for microgravity research, suborbital launches, and orbital spaceflight.',
    searchTerms: ['Swedish National Space Agency', 'SNSA', 'Rymdstyrelsen', 'Esrange', 'Sweden space'],
    keyMissions: ['Esrange Spaceport Orbital Launch Site', 'MATS Atmospheric Satellite', 'Odin Satellite Observatory'],
  },
  {
    slug: 'sso-switzerland',
    acronym: 'SSO',
    name: 'Swiss Space Office (State Secretariat for Education, Research and Innovation)',
    country: 'Switzerland',
    region: 'Europe',
    flag: '🇨🇭',
    headquarters: 'Bern, Switzerland',
    established: '1998',
    website: 'https://www.sbfi.admin.ch/space',
    description:
      'Directs Switzerland’s space participation in ESA and international missions, high-precision atomic clocks for Galileo satellites, CHEOPS exoplanet telescope leadership, and ClearSpace orbital debris removal.',
    searchTerms: ['Swiss Space Office', 'SSO', 'Switzerland space', 'CHEOPS', 'ClearSpace', 'SwissCube'],
    keyMissions: ['CHEOPS Exoplanet Characterisation Satellite', 'ClearSpace-1 Active Debris Removal', 'Galileo Atomic Clocks'],
  },
  {
    slug: 'tua',
    acronym: 'TUA',
    name: 'Turkish Space Agency (Türkiye Uzay Ajansı)',
    country: 'Türkiye',
    region: 'Europe',
    flag: '🇹🇷',
    headquarters: 'Ankara, Türkiye',
    established: '2018',
    website: 'https://tua.gov.tr',
    description:
      'Coordinates Turkey’s National Space Program including astronaut missions to the ISS (Axiom-3), indigenous rockets (Roketsan), Türksat communications satellites, and the AYAP lunar mission.',
    searchTerms: ['Turkish Space Agency', 'TUA', 'Turkiye space', 'Alper Gezeravci', 'Turksat', 'IMECE', 'AYAP'],
    keyMissions: ['National Lunar Mission (AYAP)', 'IMECE High-Resolution Earth Observation', 'Axiom-3 Turkish Astronaut Mission'],
  },
  {
    slug: 'ssau',
    acronym: 'SSAU',
    name: 'State Space Agency of Ukraine (Державне космічне агентство України)',
    country: 'Ukraine',
    region: 'Europe',
    flag: '🇺🇦',
    headquarters: 'Kyiv, Ukraine',
    established: '1992',
    website: 'https://www.nkau.gov.ua',
    description:
      'Pioneering rocket engineering hub (Yuzhnoye Design Office, Yuzhmash) famous for Zenit, Dnepr, Cyclone rockets, Antares first-stage core structures, and Vega upper-stage rocket engines.',
    searchTerms: ['State Space Agency of Ukraine', 'SSAU', 'Ukraine space', 'Yuzhnoye', 'Zenit', 'Antares stage'],
    keyMissions: ['Sich-2-30 Earth Observation Satellite', 'Antares Core Stage Engineering', 'Vega Rocket Upper Stage RD-843'],
  },
  {
    slug: 'uksa',
    acronym: 'UK Space Agency',
    name: 'United Kingdom Space Agency (UKSA)',
    country: 'United Kingdom',
    region: 'Europe',
    flag: '🇬🇧',
    headquarters: 'Swindon, United Kingdom',
    established: '2010',
    website: 'https://www.gov.uk/government/organisations/uk-space-agency',
    description:
      'Executive agency of the UK government fostering the commercial space economy, small satellite manufacturing, regional spaceports (SaxaVord, Sutherland), and major contributions to ESA science and Artemis.',
    searchTerms: ['UK Space Agency', 'UKSA', 'Britain space', 'SaxaVord', 'Sutherland', 'OneWeb', 'Vigil'],
    keyMissions: ['Vigil Space Weather Mission Support', 'UK Spaceports Program', 'Lunar Pathfinder Communications Satellite'],
  },
  {
    slug: 'lithuanian-space',
    acronym: 'Lithuanian Space Agency',
    name: 'Lithuanian Space Association & Innovation Agency Lithuania',
    country: 'Lithuania',
    region: 'Europe',
    flag: '🇱🇹',
    headquarters: 'Vilnius, Lithuania',
    established: '2007',
    website: 'https://space.lt',
    description:
      'Lithuania’s aerospace association and government agency driving nanosatellite technology (LituanicaSAT-1, LituanicaSAT-2), advanced optics, and ESA Associate Membership.',
    searchTerms: ['Lithuanian Space Association', 'Lithuania space', 'LituanicaSAT', 'Vilnius space'],
    keyMissions: ['LituanicaSAT Nanosatellite Constellation', 'ESA Associate Membership Integration', 'Laser Optical Space Payloads'],
  },

  // =========================================================================
  // MIDDLE EAST
  // =========================================================================
  {
    slug: 'nssa-bahrain',
    acronym: 'NSSA',
    name: 'National Space Science Agency of Bahrain',
    country: 'Bahrain',
    region: 'Middle East',
    flag: '🇧🇭',
    headquarters: 'Manama, Bahrain',
    established: '2014',
    website: 'https://www.nssa.gov.bh',
    description:
      'Bahrain’s government space agency promoting space science research, satellite monitoring, and joint cube satellite missions including Light-1 with the UAE and the upcoming Al-Munther satellite.',
    searchTerms: ['NSSA Bahrain', 'Bahrain space', 'Light-1 satellite', 'Al-Munther', 'Manama space'],
    keyMissions: ['Light-1 Terrestrial Gamma-Ray Flash Satellite', 'Al-Munther National Satellite', 'Space Data Analytics Lab'],
  },
  {
    slug: 'isa-iran',
    acronym: 'ISA (Iran)',
    name: 'Iranian Space Agency (سازمان فضایی ایران)',
    country: 'Iran',
    region: 'Middle East',
    flag: '🇮🇷',
    headquarters: 'Tehran, Iran',
    established: '2004',
    website: 'https://isa.ir',
    description:
      'Iran’s national agency for civilian space activities, operating indigenous Simorgh, Qaim, and Safir launch systems and the Pars, Nahid, and Khayyam Earth observation satellites.',
    searchTerms: ['Iranian Space Agency', 'ISA Iran', 'Iran space', 'Khayyam satellite', 'Simorgh rocket', 'Pars satellite'],
    keyMissions: ['Khayyam Earth Observation Satellite', 'Pars-1 Remote Sensing Satellite', 'Simorgh Launch Vehicle'],
  },
  {
    slug: 'israel-space-agency',
    acronym: 'ISA (Israel)',
    name: 'Israel Space Agency',
    country: 'Israel',
    region: 'Middle East',
    flag: '🇮🇱',
    headquarters: 'Tel Aviv, Israel',
    established: '1983',
    website: 'https://www.space.gov.il',
    description:
      'Government agency directing civilian space innovation, including the Beresheet lunar lander project, ultra-lightweight Ofeq and Venus micro-satellites, and the ULTRASAT ultraviolet space telescope.',
    searchTerms: ['Israel Space Agency', 'ISA Israel', 'Beresheet', 'ULTRASAT', 'SpaceIL', 'Venus satellite'],
    keyMissions: ['ULTRASAT Ultraviolet Space Telescope', 'Beresheet-2 Lunar Project', 'VENµS Micro-satellite'],
  },
  {
    slug: 'ssa-saudi',
    acronym: 'Saudi Space Agency',
    name: 'Saudi Space Agency (وكالة الفضاء السعودية)',
    country: 'Saudi Arabia',
    region: 'Middle East',
    flag: '🇸🇦',
    headquarters: 'Riyadh, Saudi Arabia',
    established: '2018',
    website: 'https://ssa.gov.sa',
    description:
      'Directs the Kingdom’s Vision 2030 space ambitions, including human spaceflight to the ISS (Rayyanah Barnawi, Ali AlQarni), Artemis Accords participation, and deep space research.',
    searchTerms: ['Saudi Space Agency', 'SSA Saudi', 'Saudi space', 'Rayyanah Barnawi', 'Ali AlQarni', 'Vision 2030 space'],
    keyMissions: ['Axiom-2 Saudi Astronaut Mission to ISS', 'Artemis Accords Lunar Partnerships', 'Space Debris Monitoring'],
  },
  {
    slug: 'gors-syria',
    acronym: 'GORS',
    name: 'General Organization of Remote Sensing (Syrian Space Agency)',
    country: 'Syria',
    region: 'Middle East',
    flag: '🇸🇾',
    headquarters: 'Damascus, Syria',
    established: '1986',
    website: '',
    description:
      'Syria’s state organization for space research and remote sensing applications in agriculture, geological surveys, and environmental monitoring.',
    searchTerms: ['GORS', 'Syrian Space Agency', 'Syria space', 'Damascus remote sensing'],
    keyMissions: ['Remote Sensing Environmental Monitoring', 'Geological Cartography Surveys'],
  },
  {
    slug: 'uaesa-mbrsc',
    acronym: 'UAESA / MBRSC',
    name: 'United Arab Emirates Space Agency & Mohammed Bin Rashid Space Centre',
    country: 'United Arab Emirates',
    region: 'Middle East',
    flag: '🇦🇪',
    headquarters: 'Abu Dhabi & Dubai, UAE',
    established: '2014',
    website: 'https://space.gov.ae',
    description:
      'UAE’s visionary space authorities behind the Hope Probe (Emirates Mars Mission), Rashid lunar rovers, upcoming Asteroid Belt Explorer (EMA), and astronaut Sultan Al Neyadi’s historic ISS expedition.',
    searchTerms: ['UAE Space Agency', 'UAESA', 'MBRSC', 'Hope Probe', 'Emirates Mars Mission', 'Rashid Rover', 'Sultan Al Neyadi', 'EMA Asteroid'],
    keyMissions: ['Hope Probe (Emirates Mars Mission)', 'Emirates Mission to the Asteroid Belt (EMA)', 'MBR Space Centre Lunar Rovers', 'MBZ-SAT Optical Satellite'],
  },

  // =========================================================================
  // ASIA
  // =========================================================================
  {
    slug: 'sparrso',
    acronym: 'SPARRSO',
    name: 'Space Research and Remote Sensing Organization',
    country: 'Bangladesh',
    region: 'Asia',
    flag: '🇧🇩',
    headquarters: 'Dhaka, Bangladesh',
    established: '1980',
    website: 'http://www.sparrso.gov.bd',
    description:
      'Bangladesh’s autonomous agency for peaceful applications of space science, remote sensing for delta agriculture and cyclone monitoring, in coordination with the Bangabandhu satellite network.',
    searchTerms: ['SPARRSO', 'Bangladesh space', 'Bangabandhu Satellite', 'Dhaka space agency'],
    keyMissions: ['Bangabandhu-1 Satellite Operations Support', 'Bay of Bengal Space Remote Sensing & Cyclone Tracking'],
  },
  {
    slug: 'cnsa',
    acronym: 'CNSA / CMSA',
    name: 'China National Space Administration & China Manned Space Agency',
    country: 'China',
    region: 'Asia',
    flag: '🇨🇳',
    headquarters: 'Haidian, Beijing, China',
    established: '1993',
    website: 'http://www.cnsa.gov.cn',
    description:
      'China’s national space authorities directing the Tiangong Space Station, Chang’e lunar sample return & south pole missions, Tianwen Mars probes, and Long March launch vehicles.',
    searchTerms: ['China National Space Administration', 'CNSA', 'CMSA', 'Tiangong', 'Chang\'e', 'Tianwen', 'Long March', 'Zhurong', 'Shenzhou'],
    keyMissions: ['Tiangong Orbital Space Station', 'Chang’e 6 Lunar Far Side Sample Return', 'Tianwen-3 Mars Sample Return', 'Long March 9 Super Heavy'],
  },
  {
    slug: 'isro',
    acronym: 'ISRO',
    name: 'Indian Space Research Organisation',
    country: 'India',
    region: 'Asia',
    flag: '🇮🇳',
    headquarters: 'Bengaluru, Karnataka, India',
    established: '1969',
    website: 'https://www.isro.gov.in',
    description:
      'India’s primary space agency, globally celebrated for the historic Chandrayaan-3 lunar south pole landing, Aditya-L1 solar observatory, Gaganyaan human spaceflight program, and highly reliable PSLV/LVM3 launch vehicles.',
    searchTerms: ['Indian Space Research Organisation', 'ISRO', 'Chandrayaan', 'Gaganyaan', 'Aditya-L1', 'PSLV', 'LVM3', 'SSLV', 'Mangalyaan', 'Shukrayaan'],
    keyMissions: ['Chandrayaan-3 Lunar South Pole Landing', 'Aditya-L1 Solar Observatory', 'Gaganyaan Crewed Spaceflight', 'NISAR with NASA'],
  },
  {
    slug: 'brin-lapan',
    acronym: 'BRIN / LAPAN',
    name: 'National Research and Innovation Agency (formerly LAPAN)',
    country: 'Indonesia',
    region: 'Asia',
    flag: '🇮🇩',
    headquarters: 'Jakarta, Indonesia',
    established: '1963',
    website: 'https://www.brin.go.id',
    description:
      'Indonesia’s central research and space agency operating remote sensing networks, satellite development (LAPAN-A series), and planning the Biak equatorial spaceport.',
    searchTerms: ['BRIN', 'LAPAN', 'Indonesia space', 'LAPAN-A', 'Biak spaceport'],
    keyMissions: ['LAPAN-A3 Micro-Satellite', 'Biak Equatorial Spaceport Initiative', 'Tropical Forestry Space Monitoring'],
  },
  {
    slug: 'jaxa',
    acronym: 'JAXA',
    name: 'Japan Aerospace Exploration Agency',
    country: 'Japan',
    region: 'Asia',
    flag: '🇯🇵',
    headquarters: 'Chofu, Tokyo, Japan',
    established: '2003',
    website: 'https://global.jaxa.jp',
    description:
      'Japan’s national aerospace agency renowned for asteroid sample returns (Hayabusa/Hayabusa2), precision Moon landers (SLIM), XRISM X-ray observatory, H3 launch vehicle, and the Kibo ISS module.',
    searchTerms: ['Japan Aerospace Exploration Agency', 'JAXA', 'Hayabusa', 'SLIM Moon', 'XRISM', 'H3 rocket', 'Kibo module', 'MMX Mars'],
    keyMissions: ['SLIM Pinpoint Lunar Lander', 'XRISM X-Ray Space Telescope', 'MMX Martian Moons Explorer', 'H3 Launch Vehicle'],
  },
  {
    slug: 'kazcosmos',
    acronym: 'KazCosmos',
    name: 'Kazakhstan National Space Agency (KazCosmos)',
    country: 'Kazakhstan',
    region: 'Asia',
    flag: '🇰🇿',
    headquarters: 'Astana, Kazakhstan',
    established: '2007',
    website: 'https://gharysh.kz',
    description:
      'The National Space Agency of Kazakhstan, home to the historic Baikonur Cosmodrome, operating KazSat communications and KazEOSat Earth observation satellites.',
    searchTerms: ['Kazcosmos', 'KazCosmos', 'Kazakhstan space', 'Baikonur', 'KazSat', 'KazEOSat'],
    keyMissions: ['Baiterek Green Rocket Complex at Baikonur', 'KazEOSat Earth Observation Constellation', 'KazSat-3 Telecom'],
  },
  {
    slug: 'mysa',
    acronym: 'MYSA',
    name: 'Malaysian Space Agency (Agensi Angkasa Malaysia)',
    country: 'Malaysia',
    region: 'Asia',
    flag: '🇲🇾',
    headquarters: 'Kuala Lumpur, Malaysia',
    established: '2002',
    website: 'https://www.mysa.gov.my',
    description:
      'Malaysia’s government space agency developing national space infrastructure, RazakSAT satellite programs, and downstream Earth observation applications for Southeast Asia.',
    searchTerms: ['MYSA', 'Malaysian Space Agency', 'Malaysia space', 'Angkasa', 'RazakSAT'],
    keyMissions: ['National Space Policy 2030', 'TiungSAT and RazakSAT Line', 'Equatorial Satellite Ground Station'],
  },
  {
    slug: 'msa-mongolia',
    acronym: 'Mongolian Space Agency',
    name: 'Mongolian Space Agency & Ministry of Digital Development',
    country: 'Mongolia',
    region: 'Asia',
    flag: '🇲🇳',
    headquarters: 'Ulaanbaatar, Mongolia',
    established: '2022',
    website: '',
    description:
      'Mongolia’s state body for aerospace development, operating Mazaalai cubesats, high-latitude space situational awareness, and the National Satellite Communications Project.',
    searchTerms: ['Mongolian Space Agency', 'Mongolia space', 'Mazaalai satellite', 'Ulaanbaatar space'],
    keyMissions: ['National High-Throughput Satellite', 'Mazaalai CubeSat Education Series', 'Steppe Space Science Program'],
  },
  {
    slug: 'nata-north-korea',
    acronym: 'NATA (formerly NADA)',
    name: 'National Aerospace Technology Administration',
    country: 'North Korea',
    region: 'Asia',
    flag: '🇰🇵',
    headquarters: 'Pyongyang, North Korea',
    established: '2013',
    website: '',
    description:
      'North Korea’s government aerospace agency directing the Malligyong military reconnaissance satellite series and Chollima-1 launch vehicles from Sohae.',
    searchTerms: ['NATA North Korea', 'NADA', 'Malligyong', 'Chollima rocket', 'North Korea space'],
    keyMissions: ['Malligyong Reconnaissance Satellites', 'Chollima-1 Launch Vehicle'],
  },
  {
    slug: 'suparco',
    acronym: 'SUPARCO',
    name: 'Space and Upper Atmosphere Research Commission',
    country: 'Pakistan',
    region: 'Asia',
    flag: '🇵🇰',
    headquarters: 'Karachi & Islamabad, Pakistan',
    established: '1961',
    website: 'https://suparco.gov.pk',
    description:
      'Pakistan’s executive space authority operating the PakSAT communications and PRSS remote sensing satellite constellations, with student lunar payload participation on Chang’e 6.',
    searchTerms: ['SUPARCO', 'Pakistan space', 'PakSAT', 'PRSS-1', 'ICUBE-Q'],
    keyMissions: ['PakSAT-MM1 High Throughput Satellite', 'PRSS-1 Earth Observation', 'ICUBE-Q Lunar Orbiter CubeSat'],
  },
  {
    slug: 'philsa',
    acronym: 'PhilSA',
    name: 'Philippine Space Agency',
    country: 'Philippines',
    region: 'Asia',
    flag: '🇵🇭',
    headquarters: 'Quezon City, Philippines',
    established: '2019',
    website: 'https://philsa.gov.ph',
    description:
      'The central government space agency of the Philippines directing the Diwata microsatellite and Maya cubesat programs, maritime surveillance, and disaster resilience space applications.',
    searchTerms: ['PhilSA', 'Philippine Space Agency', 'Philippines space', 'Diwata', 'Maya CubeSat', 'MULA'],
    keyMissions: ['Multispectral Unit for Land Assessment (MULA)', 'Diwata Microsatellites', 'Maya CubeSat Fleet'],
  },
  {
    slug: 'ostin-singapore',
    acronym: 'NSAS / OSTIn / CRISP',
    name: 'Office for Space Technology & Industry / National Space Agency of Singapore',
    country: 'Singapore',
    region: 'Asia',
    flag: '🇸🇬',
    headquarters: 'Singapore',
    established: '2013',
    website: 'https://www.ostin.gov.sg',
    description:
      'Singapore’s national space office directing satellite technologies (TeLEOS optical & radar satellites, NeuSAR), space domain awareness, and NewSpace incubation.',
    searchTerms: ['OSTIn', 'NSAS', 'CRISP Singapore', 'Singapore space', 'TeLEOS', 'NeuSAR'],
    keyMissions: ['TeLEOS Earth Observation SAR Fleet', 'NeuSAR Commercial Micro-Satellites', 'Singapore Space Technology Incubation'],
  },
  {
    slug: 'kasa-kari',
    acronym: 'KASA / KARI / KASI',
    name: 'Korea AeroSpace Administration & Korea Aerospace Research Institute',
    country: 'South Korea',
    region: 'Asia',
    flag: '🇰🇷',
    headquarters: 'Sacheon & Daejeon, South Korea',
    established: '1989',
    website: 'https://www.kasa.go.kr',
    description:
      'South Korea’s newly established centralized space administration supervising the indigenous Nuri (KSLV-II) rocket, Danuri lunar orbiter, KOMPSAT satellites, and future robotic lunar landings.',
    searchTerms: ['KASA', 'KARI', 'KASI', 'South Korea space', 'Nuri rocket', 'Danuri moon', 'KOMPSAT'],
    keyMissions: ['Nuri (KSLV-II) Sovereign Launch Vehicle', 'Danuri (KPLO) Lunar Orbiter', 'Next-Gen Lunar Lander 2032'],
  },
  {
    slug: 'tasa-taiwan',
    acronym: 'TASA',
    name: 'Taiwan Space Agency (formerly NSPO)',
    country: 'Taiwan',
    region: 'Asia',
    flag: '🇹🇼',
    headquarters: 'Hsinchu, Taiwan',
    established: '1991',
    website: 'https://www.tasa.org.tw',
    description:
      'Taiwan’s dedicated space agency developing the FORMOSAT optical and meteorological satellite constellations, the Triton ocean wind satellite, and sovereign orbital rocket capabilities.',
    searchTerms: ['Taiwan Space Agency', 'TASA', 'NSPO', 'FORMOSAT', 'Triton satellite', 'Taiwan space'],
    keyMissions: ['FORMOSAT-8 High-Resolution Optical Fleet', 'Triton Ocean Wind Reflector', 'B5G Low Earth Orbit Telecom Constellation'],
  },
  {
    slug: 'gistda',
    acronym: 'GISTDA',
    name: 'Geo-Informatics and Space Technology Development Agency',
    country: 'Thailand',
    region: 'Asia',
    flag: '🇹🇭',
    headquarters: 'Bangkok & Chonburi, Thailand',
    established: '2000',
    website: 'https://www.gistda.or.th',
    description:
      'Thailand’s space agency operating the THEOS and THEOS-2 high-resolution optical satellites and the Space Krenovation Park for Southeast Asian space technology incubation.',
    searchTerms: ['GISTDA', 'Thailand space', 'THEOS-2', 'THEOS', 'Space Krenovation Park'],
    keyMissions: ['THEOS-2 Earth Observation Satellite', 'AESP National Spaceport Study', 'Space Technology Park'],
  },
  {
    slug: 'tnsa-turkmenistan',
    acronym: 'TNSA',
    name: 'Turkmenistan National Space Agency & TürkmenHemrasy',
    country: 'Turkmenistan',
    region: 'Asia',
    flag: '🇹🇲',
    headquarters: 'Ashgabat, Turkmenistan',
    established: '2011',
    website: '',
    description:
      'Turkmenistan’s national space agency overseeing the TürkmenÄlem 52°E communications satellite providing broadband and broadcast services across Central Asia, Europe, and North Africa.',
    searchTerms: ['TNSA', 'Turkmenistan space', 'TurkmenAlem', 'Ashgabat space'],
    keyMissions: ['TürkmenÄlem 52°E Communications Satellite', 'Central Asian Space Geodesy'],
  },
  {
    slug: 'uzbekcosmos',
    acronym: 'Uzbekcosmos',
    name: 'Space Research and Technology Agency (Uzbekcosmos)',
    country: 'Uzbekistan',
    region: 'Asia',
    flag: '🇺🇿',
    headquarters: 'Tashkent, Uzbekistan',
    established: '2019',
    website: 'https://uzspace.uz',
    description:
      'Uzbekistan’s national space agency advancing satellite Earth remote sensing for agricultural monitoring, water basin management in the Aral Sea, and space education.',
    searchTerms: ['Uzbekcosmos', 'Uzbekistan space', 'Tashkent space agency', 'Aral Sea space monitoring'],
    keyMissions: ['National Space Remote Sensing GIS System', 'Aral Sea Basin Environmental Monitoring', 'Uzbek Space Exploration Youth Academy'],
  },
  {
    slug: 'vnsc',
    acronym: 'VNSC',
    name: 'Vietnam National Space Center',
    country: 'Vietnam',
    region: 'Asia',
    flag: '🇻🇳',
    headquarters: 'Hanoi, Vietnam',
    established: '2011',
    website: 'https://vnsc.org.vn',
    description:
      'Vietnam’s national space center managing LOTUSat radar satellites, the Hoa Lac Space Center, and astronomical observatories in Nha Trang and Hanoi.',
    searchTerms: ['Vietnam National Space Center', 'VNSC', 'Vietnam space', 'LOTUSat-1', 'PicoDragon'],
    keyMissions: ['LOTUSat-1 Earth Observation SAR Satellite', 'Hoa Lac Space Center', 'MicroDragon Satellite'],
  },

  // =========================================================================
  // OCEANIA
  // =========================================================================
  {
    slug: 'australian-space-agency',
    acronym: 'Australian Space Agency (ASA)',
    name: 'Australian Space Agency',
    country: 'Australia',
    region: 'Oceania',
    flag: '🇦🇺',
    headquarters: 'Adelaide, South Australia',
    established: '2018',
    website: 'https://www.space.gov.au',
    description:
      'Australia’s national space agency leading the "Roo-ver" semi-autonomous lunar rover for NASA’s Artemis missions, space situational awareness in the Southern Hemisphere, and regional spaceports.',
    searchTerms: ['Australian Space Agency', 'ASA Australia', 'Australia space', 'Roo-ver', 'Grose rover', 'Kanyini', 'Adelaide space'],
    keyMissions: ['Roo-ver Australian Lunar Rover for Artemis', 'Kanyini Earth Observation Satellite', 'Southern Space Launch Facilities'],
  },
  {
    slug: 'new-zealand-space-agency',
    acronym: 'New Zealand Space Agency (NZSA)',
    name: 'New Zealand Space Agency',
    country: 'New Zealand',
    region: 'Oceania',
    flag: '🇳🇿',
    headquarters: 'Wellington, New Zealand',
    established: '2016',
    website: 'https://www.mbie.govt.nz/science-and-technology/space',
    description:
      'Regulates and promotes New Zealand’s thriving commercial launch industry centered around Rocket Lab’s Launch Complex 1 on the Māhia Peninsula, and leads the MethaneSAT climate satellite operations.',
    searchTerms: ['New Zealand Space Agency', 'NZSA', 'New Zealand space', 'Mahia Peninsula', 'Rocket Lab New Zealand', 'MethaneSAT'],
    keyMissions: ['MethaneSAT Mission Operations Control', 'Māhia Peninsula Orbital Spaceport Regulation', 'Artemis Accords Collaboration'],
  },

  // =========================================================================
  // REGIONAL / INTERNATIONAL BODIES
  // =========================================================================
  {
    slug: 'esa',
    acronym: 'ESA',
    name: 'European Space Agency',
    country: 'Europe (Multinational, 22+ Member States)',
    region: 'International Bodies',
    flag: '🇪🇺',
    headquarters: 'Paris, France',
    established: '1975',
    website: 'https://www.esa.int',
    description:
      'An intergovernmental organisation of 22 member states dedicated to space exploration, world-leading science missions (Euclid, Gaia, Juice, BepiColombo), the Copernicus Earth monitoring fleet, and Ariane launchers.',
    searchTerms: ['European Space Agency', 'ESA', 'Ariane', 'Euclid', 'Juice', 'BepiColombo', 'Gaia', 'Copernicus', 'Sentinel'],
    keyMissions: ['Euclid Dark Universe Observatory', 'Juice Jupiter Moons Explorer', 'Ariane 6', 'Copernicus Sentinels'],
  },
  {
    slug: 'euspa',
    acronym: 'EUSPA',
    name: 'European Union Agency for the Space Programme',
    country: 'European Union',
    region: 'International Bodies',
    flag: '🇪🇺',
    headquarters: 'Prague, Czech Republic',
    established: '2021',
    website: 'https://www.euspa.europa.eu',
    description:
      'The operational European Union agency managing EU space infrastructure, including Galileo satellite navigation, EGNOS, Copernicus market uptake, GOVSATCOM secure communications, and the IRIS² sovereign satellite constellation.',
    searchTerms: ['EUSPA', 'European Union Space Programme', 'Galileo satellite', 'EGNOS', 'IRIS2', 'Prague space'],
    keyMissions: ['Galileo Global Navigation Satellite System', 'Copernicus Market & Downstream Uptake', 'IRIS² Sovereign Secure Satellite Constellation'],
  },
  {
    slug: 'apsco',
    acronym: 'APSCO',
    name: 'Asia-Pacific Space Cooperation Organization',
    country: 'Asia-Pacific Intergovernmental',
    region: 'International Bodies',
    flag: '🌐',
    headquarters: 'Beijing, China',
    established: '2008',
    website: 'http://www.apsco.int',
    description:
      'Intergovernmental space organization promoting multilateral space science, joint satellite constellations (Student Small Satellite project SSS), and space education across member states in the Asia-Pacific region.',
    searchTerms: ['APSCO', 'Asia-Pacific Space Cooperation', 'APSCO satellite', 'Multilateral space'],
    keyMissions: ['APSCO Student Small Satellite (SSS) Constellation', 'Joint Optical Satellite Space Tracking Network (APOSOS)'],
  },
  {
    slug: 'unoosa',
    acronym: 'UNOOSA',
    name: 'United Nations Office for Outer Space Affairs',
    country: 'United Nations',
    region: 'International Bodies',
    flag: '🇺🇳',
    headquarters: 'Vienna International Centre, Vienna, Austria',
    established: '1958',
    website: 'https://www.unoosa.org',
    description:
      'The United Nations office promoting international cooperation in the peaceful uses of outer space, maintaining the official UN Register of Objects Launched into Outer Space, and implementing the UN space treaties.',
    searchTerms: ['UNOOSA', 'United Nations Space', 'UN Register space', 'World Space Forum', 'Outer Space Treaty'],
    keyMissions: ['UN Register of Objects Launched into Outer Space', 'Space4SDGs Development Initiative', 'Access to Space for All Initiative'],
  },
  {
    slug: 'uncopuos',
    acronym: 'UNCOPUOS',
    name: 'United Nations Committee on the Peaceful Uses of Outer Space',
    country: 'United Nations',
    region: 'International Bodies',
    flag: '🇺🇳',
    headquarters: 'Vienna, Austria',
    established: '1959',
    website: 'https://www.unoosa.org/oosa/en/ourwork/copuos/index.html',
    description:
      'The principal UN committee governing the exploration and use of space for the benefit of humanity, establishing guidelines for long-term sustainability of space activities, space debris mitigation, and lunar governance.',
    searchTerms: ['UNCOPUOS', 'COPUOS', 'Peaceful Uses of Outer Space', 'Space Debris Guidelines', 'Lunar governance UN'],
    keyMissions: ['Guidelines for the Long-term Sustainability of Outer Space Activities', 'Space Debris Mitigation Standards', 'Planetary Defense Coordination'],
  },
]

export const REGIONS: Region[] = [
  'Africa',
  'North & Central America',
  'South America',
  'Europe',
  'Middle East',
  'Asia',
  'Oceania',
  'International Bodies',
]

export function getAllAgencies(): SpaceAgency[] {
  return SPACE_AGENCIES
}

export function getAgencyBySlug(slug: string): SpaceAgency | undefined {
  const normalized = (slug || '').toLowerCase().trim()
  return SPACE_AGENCIES.find(
    (a) => a.slug.toLowerCase() === normalized || a.acronym.toLowerCase() === normalized
  )
}

export function getAgenciesByRegion(region: Region): SpaceAgency[] {
  return SPACE_AGENCIES.filter((a) => a.region === region)
}
