export type Region =
  | 'North America'
  | 'South America'
  | 'Europe'
  | 'Asia'
  | 'Africa'
  | 'Oceania'

export interface SpaceAgency {
  slug: string
  acronym: string
  name: string
  country: string
  region: Region
  flag: string
  headquarters?: string
  established?: string
  website?: string
  description: string
  searchTerms: string[]
  keyMissions?: string[]
}

export const SPACE_AGENCIES: SpaceAgency[] = [
  // -------------------------------------------------------------
  // NORTH AMERICA
  // -------------------------------------------------------------
  {
    slug: 'nasa',
    acronym: 'NASA',
    name: 'National Aeronautics and Space Administration',
    country: 'United States',
    region: 'North America',
    flag: '🇺🇸',
    headquarters: 'Washington, D.C., USA',
    established: '1958',
    website: 'https://www.nasa.gov',
    description:
      'The civilian space agency of the United States government responsible for the civilian space program, aeronautics research, and space exploration including the Artemis lunar campaign, James Webb Space Telescope, and Mars exploration rovers.',
    searchTerms: ['NASA', 'Artemis', 'Perseverance', 'Curiosity', 'James Webb', 'JWST', 'Hubble', 'Kennedy Space Center', 'JPL', 'Goddard'],
    keyMissions: ['Artemis Program', 'James Webb Space Telescope', 'Perseverance Mars Rover', 'Europa Clipper', 'Commercial Crew'],
  },
  {
    slug: 'csa-asc',
    acronym: 'CSA/ASC',
    name: 'Canadian Space Agency / Agence spatiale canadienne',
    country: 'Canada',
    region: 'North America',
    flag: '🇨🇦',
    headquarters: 'Longueuil, Quebec, Canada',
    established: '1989',
    website: 'https://www.asc-csa.gc.ca',
    description:
      'Canada’s national space agency, leader in advanced space robotics (Canadarm, Canadarm2, Canadarm3), satellite Earth observation (RADARSAT), and astronaut participation in the Artemis and ISS programs.',
    searchTerms: ['Canadian Space Agency', 'CSA', 'Canadarm', 'Jeremy Hansen', 'RADARSAT', 'ASC'],
    keyMissions: ['Canadarm3 (Lunar Gateway)', 'Artemis II (Jeremy Hansen)', 'RADARSAT Constellation', 'NEOSSat'],
  },
  {
    slug: 'aem',
    acronym: 'AEM',
    name: 'Agencia Espacial Mexicana',
    country: 'Mexico',
    region: 'North America',
    flag: '🇲🇽',
    headquarters: 'Mexico City, Mexico',
    established: '2010',
    website: 'https://www.gob.mx/aem',
    description:
      'Mexico’s decentralized space agency coordinating national space infrastructure, Earth observation applications, scientific research, and international partnerships in Latin America and the Artemis Accords.',
    searchTerms: ['Agencia Espacial Mexicana', 'AEM', 'Mexico space', 'Colmena', 'AztechSat'],
    keyMissions: ['AztechSat Nano-satellites', 'Colmena Lunar Micro-Robotics', 'Earth Observation Network'],
  },

  // -------------------------------------------------------------
  // SOUTH AMERICA
  // -------------------------------------------------------------
  {
    slug: 'aeb',
    acronym: 'AEB',
    name: 'Agência Espacial Brasileira',
    country: 'Brazil',
    region: 'South America',
    flag: '🇧🇷',
    headquarters: 'Brasília, Brazil',
    established: '1994',
    website: 'https://www.gov.br/aeb',
    description:
      'The Brazilian Space Agency oversees civil space development, the Alcântara Launch Center near the equator, CBERS Earth observation satellites with China, and Amazon environmental monitoring.',
    searchTerms: ['Agencia Espacial Brasileira', 'AEB', 'Brazil space', 'Alcantara', 'CBERS', 'Amazonia-1'],
    keyMissions: ['Amazonia-1', 'CBERS Satellite Series', 'Alcântara Space Center Spaceport'],
  },
  {
    slug: 'conae',
    acronym: 'CONAE',
    name: 'Comisión Nacional de Actividades Espaciales',
    country: 'Argentina',
    region: 'South America',
    flag: '🇦🇷',
    headquarters: 'Buenos Aires, Argentina',
    established: '1991',
    website: 'https://www.argentina.gob.ar/ciencia/conae',
    description:
      'Argentina’s civilian space agency specializing in advanced synthetic aperture radar (SAR) Earth observation satellites (SAOCOM series) and satellite engineering through INVAP.',
    searchTerms: ['CONAE', 'Argentina space', 'SAOCOM', 'Tronador', 'SABIA-Mar'],
    keyMissions: ['SAOCOM 1A/1B Radar Constellation', 'SABIA-Mar Ocean Observation', 'Tronador Rocket Project'],
  },
  {
    slug: 'abae',
    acronym: 'ABAE',
    name: 'Agencia Bolivariana para Actividades Espaciales',
    country: 'Venezuela',
    region: 'South America',
    flag: '🇻🇪',
    headquarters: 'Caracas, Venezuela',
    established: '2007',
    website: 'http://www.abae.gob.ve',
    description:
      'Venezuela’s national space agency operating communications and remote sensing satellites, including the Venesat-1 (Simón Bolívar) and VRSS satellite programs.',
    searchTerms: ['ABAE', 'Venezuela space', 'Venesat', 'Miranda satellite', 'Sucre satellite'],
    keyMissions: ['VRSS-1 Francisco de Miranda', 'VRSS-2 Antonio José de Sucre', 'VeneSat Telecom'],
  },
  {
    slug: 'conida',
    acronym: 'CONIDA',
    name: 'Comisión Nacional de Investigación y Desarrollo Aeroespacial',
    country: 'Peru',
    region: 'South America',
    flag: '🇵🇪',
    headquarters: 'Lima, Peru',
    established: '1974',
    website: 'https://www.gob.pe/conida',
    description:
      'The Peruvian Space Agency operating the high-resolution PeruSat-1 optical Earth observation satellite and advancing astronomical research at the National Astronomical Observatory.',
    searchTerms: ['CONIDA', 'Peruvian Space Agency', 'PeruSat-1', 'Peru space'],
    keyMissions: ['PeruSat-1 High Resolution Earth Observation', 'National Center for Satellite Operations (CNOIS)'],
  },
  {
    slug: 'aec',
    acronym: 'AEC',
    name: 'Chilean Space Agency / Agencia Chilena del Espacio',
    country: 'Chile',
    region: 'South America',
    flag: '🇨🇱',
    headquarters: 'Santiago, Chile',
    established: '2001',
    website: 'https://www.defensa.cl/espacio',
    description:
      'Chile’s national space coordination entity managing the National Satellite System (SNSAT), high-altitude astronomical observatory hosting in the Atacama Desert, and space technologies.',
    searchTerms: ['AEC', 'Chilean Space Agency', 'SNSAT', 'FASat', 'Chile space'],
    keyMissions: ['National Satellite System (SNSAT)', 'FASat-Delta', 'Atacama Space Observation Support'],
  },

  // -------------------------------------------------------------
  // EUROPE
  // -------------------------------------------------------------
  {
    slug: 'esa',
    acronym: 'ESA',
    name: 'European Space Agency',
    country: 'Europe (Multinational, 22+ Member States)',
    region: 'Europe',
    flag: '🇪🇺',
    headquarters: 'Paris, France',
    established: '1975',
    website: 'https://www.esa.int',
    description:
      'An intergovernmental organisation of 22 member states dedicated to space exploration, world-leading science missions (Euclid, Gaia, Juice, BepiColombo), the Copernicus Earth monitoring fleet, and Ariane launchers.',
    searchTerms: ['European Space Agency', 'ESA', 'Ariane', 'Euclid', 'Juice', 'BepiColombo', 'Gaia', 'Copernicus', 'Sentinel'],
    keyMissions: ['Euclid Dark Universe Observatory', 'Juice Jupiter Moons Explorer', 'Ariane 6', 'Copernicus Sentinels'],
  },
  {
    slug: 'roscosmos',
    acronym: 'Roscosmos',
    name: 'State Space Corporation Roscosmos',
    country: 'Russia',
    region: 'Europe',
    flag: '🇷🇺',
    headquarters: 'Moscow, Russia',
    established: '1992',
    website: 'https://www.roscosmos.ru',
    description:
      'The Russian state corporation for space activities operating Soyuz and Progress crew and cargo flights to the ISS, GLONASS navigation constellation, and launch facilities at Baikonur and Vostochny.',
    searchTerms: ['Roscosmos', 'Soyuz', 'Progress', 'Cosmonauts', 'Vostochny', 'GLONASS', 'Baikonur'],
    keyMissions: ['Soyuz Crew Spaceflight', 'ISS Russian Orbital Segment', 'GLONASS Navigation Fleet', 'Luna Exploration'],
  },
  {
    slug: 'cnes',
    acronym: 'CNES',
    name: 'Centre National d’Études Spatiales',
    country: 'France',
    region: 'Europe',
    flag: '🇫🇷',
    headquarters: 'Paris, France',
    established: '1961',
    website: 'https://cnes.fr',
    description:
      'The French space agency, European leader in launcher development, Guiana Space Centre spaceport operations, climate science, planetary exploration instruments, and satellite innovation.',
    searchTerms: ['CNES', 'France space', 'French space agency', 'Guiana Space Centre', 'Toulouse Space Center'],
    keyMissions: ['Guiana Space Centre (CSG)', 'SWOT Water Ocean Topography', 'MicroCarb Climate Mission'],
  },
  {
    slug: 'dlr',
    acronym: 'DLR',
    name: 'German Aerospace Center (Deutsches Zentrum für Luft- und Raumfahrt)',
    country: 'Germany',
    region: 'Europe',
    flag: '🇩🇪',
    headquarters: 'Cologne, Germany',
    established: '1969',
    website: 'https://www.dlr.de',
    description:
      'Germany’s national research center for aeronautics and space conducting robotics, planetary exploration, Earth observation (TerraSAR-X, EnMAP), and human spaceflight operations.',
    searchTerms: ['DLR', 'German Aerospace Center', 'Germany space', 'EnMAP', 'TerraSAR-X'],
    keyMissions: ['Columbus Module Operations', 'EnMAP Hyperspectral Satellite', 'Robotics & Deep Space Sensors'],
  },
  {
    slug: 'asi',
    acronym: 'ASI',
    name: 'Agenzia Spaziale Italiana',
    country: 'Italy',
    region: 'Europe',
    flag: '🇮🇹',
    headquarters: 'Rome, Italy',
    established: '1988',
    website: 'https://www.asi.it',
    description:
      'The Italian Space Agency, premier developer of pressurized space station modules, COSMO-SkyMed radar constellation, Vega rocket architectures, and deep space radio science.',
    searchTerms: ['Agenzia Spaziale Italiana', 'ASI', 'Italy space', 'COSMO-SkyMed', 'Vega launcher', 'Prisma'],
    keyMissions: ['COSMO-SkyMed Second Generation Radar', 'Vega Launcher Series', 'PRISMA Hyperspectral Satellite'],
  },
  {
    slug: 'uksa',
    acronym: 'UK Space Agency',
    name: 'United Kingdom Space Agency',
    country: 'United Kingdom',
    region: 'Europe',
    flag: '🇬🇧',
    headquarters: 'Swindon, United Kingdom',
    established: '2010',
    website: 'https://www.gov.uk/government/organisations/uk-space-agency',
    description:
      'Executive agency of the UK government fostering the commercial space economy, small satellite manufacturing, regional spaceports, and major contributions to ESA science and Artemis.',
    searchTerms: ['UK Space Agency', 'UKSA', 'Britain space', 'SaxaVord', 'Sutherland', 'OneWeb'],
    keyMissions: ['Vigil Space Weather Mission Support', 'UK Spaceports Program', 'Lunar Pathfinder Communications'],
  },
  {
    slug: 'polsa',
    acronym: 'POLSA',
    name: 'Polish Space Agency (Polska Agencja Kosmiczna)',
    country: 'Poland',
    region: 'Europe',
    flag: '🇵🇱',
    headquarters: 'Gdańsk, Poland',
    established: '2014',
    website: 'https://polsa.gov.pl',
    description:
      'Poland’s national space agency supporting Polish space industry integration with ESA, space domain awareness (SDA), Earth observation, and the Artemis Accords.',
    searchTerms: ['Polish Space Agency', 'POLSA', 'Poland space', 'Polska Agencja Kosmiczna'],
    keyMissions: ['Polish Space Surveillance and Tracking', 'ESA Science Consortia', 'Ignis Micro-Satellite Systems'],
  },
  {
    slug: 'rosa',
    acronym: 'ROSA',
    name: 'Romanian Space Agency (Agenția Spațială Română)',
    country: 'Romania',
    region: 'Europe',
    flag: '🇷🇴',
    headquarters: 'Bucharest, Romania',
    established: '1991',
    website: 'https://www.rosa.ro',
    description:
      'The Romanian Space Agency coordinating national space research, planetary defense participation in ESA’s Hera mission, and space security infrastructure.',
    searchTerms: ['Romanian Space Agency', 'ROSA', 'Romania space', 'Hera mission Romania'],
    keyMissions: ['ESA Hera Planetary Defense Subsystems', 'Earth Observation Centre', 'Space Situational Awareness'],
  },
  {
    slug: 'snsa',
    acronym: 'SNSA',
    name: 'Swedish National Space Agency (Rymdstyrelsen)',
    country: 'Sweden',
    region: 'Europe',
    flag: '🇸🇪',
    headquarters: 'Solna, Sweden',
    established: '1972',
    website: 'https://www.rymdstyrelsen.se',
    description:
      'Sweden’s government agency for space activities operating the Esrange Space Center inside the Arctic Circle for microgravity research, suborbital launches, and orbital spaceflight.',
    searchTerms: ['Swedish National Space Agency', 'SNSA', 'Rymdstyrelsen', 'Esrange', 'Sweden space'],
    keyMissions: ['Esrange Spaceport Orbital Launch Site', 'MATS Atmospheric Satellite', 'Odin Satellite Observatory'],
  },
  {
    slug: 'nosa',
    acronym: 'NOSA',
    name: 'Norwegian Space Agency (Norsk Romsenter)',
    country: 'Norway',
    region: 'Europe',
    flag: '🇳🇴',
    headquarters: 'Oslo, Norway',
    established: '1987',
    website: 'https://www.romsenter.no',
    description:
      'Norway’s government agency managing satellite communications, Arctic maritime surveillance AIS fleets, Andøya Spaceport, and Svalbard satellite ground stations.',
    searchTerms: ['Norwegian Space Agency', 'NOSA', 'Norsk Romsenter', 'Andøya', 'Norway space', 'SvalSat'],
    keyMissions: ['Andøya Spaceport Orbital Infrastructure', 'Arctic Maritime Surveillance AIS Fleet', 'Svalbard Satellite Station'],
  },
  {
    slug: 'belspo',
    acronym: 'BELSPO',
    name: 'Belgian Federal Science Policy Office (Space Department)',
    country: 'Belgium',
    region: 'Europe',
    flag: '🇧🇪',
    headquarters: 'Brussels, Belgium',
    established: '1959',
    website: 'https://www.belspo.be',
    description:
      'Coordinates Belgium’s significant financial and industrial contributions to ESA, the PROBA microsatellite line, and the Euro Space Center.',
    searchTerms: ['BELSPO', 'Belgian Space', 'PROBA', 'Belgium space'],
    keyMissions: ['PROBA-3 Solar Coronagraphy Satellite', 'Euro Space Center Research', 'ESA Science Instrument Contributions'],
  },
  {
    slug: 'portugal-space',
    acronym: 'Portugal Space',
    name: 'Portuguese Space Agency (Agência Espacial Portuguesa)',
    country: 'Portugal',
    region: 'Europe',
    flag: '🇵🇹',
    headquarters: 'Lisbon & Santa Maria (Azores), Portugal',
    established: '2019',
    website: 'https://ptspace.pt',
    description:
      'Develops Portugal’s space strategy, Atlantic Constellation Earth observation satellites, and the Santa Maria spaceport initiative in the Azores.',
    searchTerms: ['Portugal Space', 'Portuguese Space Agency', 'Azores spaceport', 'Atlantic Constellation'],
    keyMissions: ['Atlantic Constellation Earth Observation', 'Santa Maria Azores Space Port Hub', 'Space Rider Landing Site'],
  },
  {
    slug: 'lsa',
    acronym: 'LSA',
    name: 'Luxembourg Space Agency',
    country: 'Luxembourg',
    region: 'Europe',
    flag: '🇱🇺',
    headquarters: 'Luxembourg City, Luxembourg',
    established: '2018',
    website: 'https://space-agency.public.lu',
    description:
      'World pioneer in commercial space resources legal frameworks, financing newspace ventures, lunar mining ecosystems (SpaceResources.lu), and space communications.',
    searchTerms: ['Luxembourg Space Agency', 'LSA', 'SpaceResources.lu', 'Luxembourg space'],
    keyMissions: ['SpaceResources.lu Lunar Mining Initiative', 'European Space Resources Innovation Centre (ESRIC)'],
  },
  {
    slug: 'cso',
    acronym: 'CSO',
    name: 'Czech Space Office (Česká kosmická kancelář)',
    country: 'Czech Republic',
    region: 'Europe',
    flag: '🇨🇿',
    headquarters: 'Prague, Czech Republic',
    established: '2003',
    website: 'https://www.czechspaceportal.cz',
    description:
      'Coordinates Czech participation in ESA programs, optical instruments for astronomical satellites, and hosts the EU Agency for the Space Programme (EUSPA) in Prague.',
    searchTerms: ['Czech Space Office', 'CSO', 'Czech space', 'EUSPA Prague', 'VZLUSAT'],
    keyMissions: ['VZLUSAT Technology Demonstrators', 'EUSPA Galileo & Copernicus Coordination', 'ESA Optical Payloads'],
  },
  {
    slug: 'hsc',
    acronym: 'HSC',
    name: 'Hellenic Space Center (Ελληνικό Κέντρο Διαστήματος)',
    country: 'Greece',
    region: 'Europe',
    flag: '🇬🇷',
    headquarters: 'Athens, Greece',
    established: '2019',
    website: 'https://hsc.gov.gr',
    description:
      'The Greek national space organization coordinating satellite communications (Hellas Sat), maritime monitoring in the Mediterranean, and national micro-satellite constellations.',
    searchTerms: ['Hellenic Space Center', 'HSC', 'Greece space', 'Hellas Sat', 'Greek space agency'],
    keyMissions: ['National Small Satellite Constellation', 'Hellas Sat Communications', 'Mediterranean Maritime Observation'],
  },
  {
    slug: 'tua',
    acronym: 'TUA',
    name: 'Turkish Space Agency (Türkiye Uzay Ajansı)',
    country: 'Türkiye',
    region: 'Europe',
    flag: '🇹🇷',
    headquarters: 'Ankara, Türkiye',
    established: '2018',
    website: 'https://tua.gov.tr',
    description:
      'Coordinates Turkey’s National Space Program including astronaut missions to the ISS, indigenous rockets (Roketsan), Türksat communications satellites, and lunar rovers.',
    searchTerms: ['Turkish Space Agency', 'TUA', 'Turkiye space', 'Alper Gezeravcı', 'Turksat', 'IMECE'],
    keyMissions: ['National Lunar Mission (AYAP)', 'IMECE Earth Observation Satellite', 'Axiom-3 Turkish Astronaut Mission'],
  },
  {
    slug: 'ssau',
    acronym: 'SSAU',
    name: 'State Space Agency of Ukraine (Державне космічне агентство України)',
    country: 'Ukraine',
    region: 'Europe',
    flag: '🇺🇦',
    headquarters: 'Kyiv, Ukraine',
    established: '1992',
    website: 'https://www.nkau.gov.ua',
    description:
      'Pioneering rocket engineering hub (Yuzhnoye Design Office, Yuzhmash) famous for Zenit, Dnepr, Cyclone rockets, Antares first-stage structures, and Vega rocket engines.',
    searchTerms: ['State Space Agency of Ukraine', 'SSAU', 'Ukraine space', 'Yuzhnoye', 'Zenit', 'Antares stage'],
    keyMissions: ['Sich-2-30 Earth Observation Satellite', 'Antares Core Stage Engineering', 'Vega Rocket Upper Stage RD-843'],
  },
  {
    slug: 'maka',
    acronym: 'MAKA / Azercosmos',
    name: 'Azerbaijan National Aerospace Agency & Azercosmos',
    country: 'Azerbaijan',
    region: 'Europe',
    flag: '🇦🇿',
    headquarters: 'Baku, Azerbaijan',
    established: '1992',
    website: 'https://azercosmos.az',
    description:
      'National space agency and premier satellite operator in the South Caucasus, operating Azerspace telecom satellites and Azersky optical Earth observation.',
    searchTerms: ['Azercosmos', 'MAKA', 'Azerbaijan space', 'Azerspace', 'Azersky'],
    keyMissions: ['Azerspace-1 and Azerspace-2 Telecom Satellites', '74th International Astronautical Congress (IAC Baku)'],
  },

  // -------------------------------------------------------------
  // ASIA
  // -------------------------------------------------------------
  {
    slug: 'cnsa',
    acronym: 'CNSA',
    name: 'China National Space Administration',
    country: 'China',
    region: 'Asia',
    flag: '🇨🇳',
    headquarters: 'Haidian, Beijing, China',
    established: '1993',
    website: 'http://www.cnsa.gov.cn',
    description:
      'China’s national space agency directing the Tiangong Space Station, Chang’e lunar sample return & south pole missions, Tianwen Mars probes, and Long March launch vehicles.',
    searchTerms: ['China National Space Administration', 'CNSA', 'Tiangong', 'Chang\'e', 'Tianwen', 'Long March', 'Zhurong', 'Shenzhou'],
    keyMissions: ['Tiangong Orbital Space Station', 'Chang’e 6 Lunar Far Side Sample Return', 'Tianwen-3 Mars Sample Return', 'Long March 9'],
  },
  {
    slug: 'isro',
    acronym: 'ISRO',
    name: 'Indian Space Research Organisation',
    country: 'India',
    region: 'Asia',
    flag: '🇮🇳',
    headquarters: 'Bengaluru, Karnataka, India',
    established: '1969',
    website: 'https://www.isro.gov.in',
    description:
      'India’s primary space agency, globally celebrated for the historic Chandrayaan-3 lunar south pole landing, Aditya-L1 solar observatory, Gaganyaan human spaceflight program, and highly reliable PSLV/LVM3 launch vehicles.',
    searchTerms: ['Indian Space Research Organisation', 'ISRO', 'Chandrayaan', 'Gaganyaan', 'Aditya-L1', 'PSLV', 'LVM3', 'SSLV', 'Mangalyaan'],
    keyMissions: ['Chandrayaan-3 Lunar South Pole Landing', 'Aditya-L1 Solar Mission', 'Gaganyaan Crewed Spaceflight', 'NISAR with NASA'],
  },
  {
    slug: 'jaxa',
    acronym: 'JAXA',
    name: 'Japan Aerospace Exploration Agency',
    country: 'Japan',
    region: 'Asia',
    flag: '🇯🇵',
    headquarters: 'Chofu, Tokyo, Japan',
    established: '2003',
    website: 'https://global.jaxa.jp',
    description:
      'Japan’s national aerospace agency renowned for asteroid sample returns (Hayabusa/Hayabusa2), precision Moon landers (SLIM), XRISM X-ray observatory, H3 launch vehicle, and the Kibo ISS module.',
    searchTerms: ['Japan Aerospace Exploration Agency', 'JAXA', 'Hayabusa', 'SLIM Moon', 'XRISM', 'H3 rocket', 'Kibo module', 'MMX Mars'],
    keyMissions: ['SLIM Pinpoint Lunar Lander', 'XRISM X-Ray Space Telescope', 'MMX Martian Moons Explorer', 'H3 Launch Vehicle'],
  },
  {
    slug: 'kari-kasa',
    acronym: 'KARI / KASA',
    name: 'Korea Aerospace Research Institute & Korea AeroSpace Administration',
    country: 'South Korea',
    region: 'Asia',
    flag: '🇰🇷',
    headquarters: 'Sacheon & Daejeon, South Korea',
    established: '1989',
    website: 'https://www.kari.re.kr',
    description:
      'South Korea’s space agency overseeing the indigenous Nuri (KSLV-II) space rocket, Danuri lunar orbiter, KOMPSAT Earth imaging satellites, and future robotic lunar landings.',
    searchTerms: ['KARI', 'KASA', 'South Korea space', 'Nuri rocket', 'Danuri moon', 'KOMPSAT'],
    keyMissions: ['Nuri (KSLV-II) Sovereign Launch Vehicle', 'Danuri (KPLO) Lunar Orbiter', 'Next-Gen Lunar Lander 2032'],
  },
  {
    slug: 'nada-nsau',
    acronym: 'NADA / NSAU',
    name: 'National Aerospace Development Administration',
    country: 'North Korea',
    region: 'Asia',
    flag: '🇰🇵',
    headquarters: 'Pyongyang, North Korea',
    established: '2013',
    website: '',
    description:
      'North Korea’s government space body overseeing the Malligyong reconnaissance satellite series and Chollima orbital launch vehicles from the Sohae Satellite Launching Ground.',
    searchTerms: ['NADA North Korea', 'Malligyong', 'Chollima rocket', 'North Korea space'],
    keyMissions: ['Malligyong Reconnaissance Satellites', 'Chollima-1 Launch Vehicle'],
  },
  {
    slug: 'suparco',
    acronym: 'SUPARCO',
    name: 'Space and Upper Atmosphere Research Commission',
    country: 'Pakistan',
    region: 'Asia',
    flag: '🇵🇰',
    headquarters: 'Karachi & Islamabad, Pakistan',
    established: '1961',
    website: 'https://suparco.gov.pk',
    description:
      'Pakistan’s executive space authority operating the PakSAT communications and PRSS remote sensing satellite constellations, with student lunar payload participation on Chang’e 6.',
    searchTerms: ['SUPARCO', 'Pakistan space', 'PakSAT', 'PRSS-1', 'ICUBE-Q'],
    keyMissions: ['PakSAT-MM1 High Throughput Satellite', 'PRSS-1 Earth Observation', 'ICUBE-Q Lunar Orbiter CubeSat'],
  },
  {
    slug: 'brin-lapan',
    acronym: 'BRIN / LAPAN',
    name: 'National Research and Innovation Agency (formerly LAPAN)',
    country: 'Indonesia',
    region: 'Asia',
    flag: '🇮🇩',
    headquarters: 'Jakarta, Indonesia',
    established: '1963',
    website: 'https://www.brin.go.id',
    description:
      'Indonesia’s central research and space agency operating remote sensing networks, satellite development (LAPAN-A series), and planning the Biak equatorial spaceport.',
    searchTerms: ['BRIN', 'LAPAN', 'Indonesia space', 'LAPAN-A', 'Biak spaceport'],
    keyMissions: ['LAPAN-A3 Micro-Satellite', 'Biak Equatorial Spaceport Initiative', 'Tropical Forestry Space Monitoring'],
  },
  {
    slug: 'mysa',
    acronym: 'MYSA',
    name: 'Malaysian Space Agency (Agensi Angkasa Malaysia)',
    country: 'Malaysia',
    region: 'Asia',
    flag: '🇲🇾',
    headquarters: 'Kuala Lumpur, Malaysia',
    established: '2002',
    website: 'https://www.mysa.gov.my',
    description:
      'Malaysia’s government space agency developing national space infrastructure, RazakSAT satellite programs, and downstream Earth observation applications for Southeast Asia.',
    searchTerms: ['MYSA', 'Malaysian Space Agency', 'Malaysia space', 'Angkasa', 'RazakSAT'],
    keyMissions: ['National Space Policy 2030', 'TiungSAT and RazakSAT Line', 'Equatorial Satellite Ground Station'],
  },
  {
    slug: 'gistda',
    acronym: 'GISTDA',
    name: 'Geo-Informatics and Space Technology Development Agency',
    country: 'Thailand',
    region: 'Asia',
    flag: '🇹🇭',
    headquarters: 'Bangkok & Chonburi, Thailand',
    established: '2000',
    website: 'https://www.gistda.or.th',
    description:
      'Thailand’s space agency operating the THEOS and THEOS-2 high-resolution optical satellites and the Space Krenovation Park for Southeast Asian space technology incubation.',
    searchTerms: ['GISTDA', 'Thailand space', 'THEOS-2', 'THEOS', 'Space Krenovation Park'],
    keyMissions: ['THEOS-2 Earth Observation Satellite', 'AESP National Spaceport Study', 'Space Technology Park'],
  },
  {
    slug: 'philsa',
    acronym: 'PhilSA',
    name: 'Philippine Space Agency',
    country: 'Philippines',
    region: 'Asia',
    flag: '🇵🇭',
    headquarters: 'Quezon City, Philippines',
    established: '2019',
    website: 'https://philsa.gov.ph',
    description:
      'The central government space agency of the Philippines directing the Diwata microsatellite and Maya cubesat programs, maritime surveillance, and disaster resilience space applications.',
    searchTerms: ['PhilSA', 'Philippine Space Agency', 'Philippines space', 'Diwata', 'Maya CubeSat'],
    keyMissions: ['Multispectral Unit for Land Assessment (MULA)', 'Diwata Microsatellites', 'Maya CubeSat Fleet'],
  },
  {
    slug: 'vnsc',
    acronym: 'VNSC',
    name: 'Vietnam National Space Center',
    country: 'Vietnam',
    region: 'Asia',
    flag: '🇻🇳',
    headquarters: 'Hanoi, Vietnam',
    established: '2011',
    website: 'https://vnsc.org.vn',
    description:
      'Vietnam’s national space center managing LOTUSat radar satellites, the Hoa Lac Space Center, and astronomical observatories in Nha Trang and Hanoi.',
    searchTerms: ['Vietnam National Space Center', 'VNSC', 'Vietnam space', 'LOTUSat-1', 'PicoDragon'],
    keyMissions: ['LOTUSat-1 Earth Observation SAR Satellite', 'Hoa Lac Space Center', 'MicroDragon Satellite'],
  },
  {
    slug: 'sparrso',
    acronym: 'SPARRSO',
    name: 'Space Research and Remote Sensing Organization',
    country: 'Bangladesh',
    region: 'Asia',
    flag: '🇧🇩',
    headquarters: 'Dhaka, Bangladesh',
    established: '1980',
    website: 'http://www.sparrso.gov.bd',
    description:
      'Bangladesh’s autonomous agency for peaceful applications of space science, remote sensing for delta agriculture and cyclone monitoring, in coordination with the Bangabandhu satellite network.',
    searchTerms: ['SPARRSO', 'Bangladesh space', 'Bangabandhu Satellite', 'Dhaka space agency'],
    keyMissions: ['Bangabandhu-1 Satellite Operations Support', 'Bay of Bengal Space Remote Sensing & Cyclone Tracking'],
  },
  {
    slug: 'israel-space-agency',
    acronym: 'ISA (Israel)',
    name: 'Israel Space Agency',
    country: 'Israel',
    region: 'Asia',
    flag: '🇮🇱',
    headquarters: 'Tel Aviv, Israel',
    established: '1983',
    website: 'https://www.space.gov.il',
    description:
      'Government agency directing civilian space innovation, including the Beresheet lunar lander project, ultra-lightweight Ofeq and Venus micro-satellites, and the ULTRASAT ultraviolet space telescope.',
    searchTerms: ['Israel Space Agency', 'ISA Israel', 'Beresheet', 'ULTRASAT', 'SpaceIL', 'Venus satellite'],
    keyMissions: ['ULTRASAT Ultraviolet Space Telescope', 'Beresheet-2 Lunar Project', 'VENµS Micro-satellite'],
  },
  {
    slug: 'isa-iran',
    acronym: 'ISA (Iran)',
    name: 'Iranian Space Agency (سازمان فضایی ایران)',
    country: 'Iran',
    region: 'Asia',
    flag: '🇮🇷',
    headquarters: 'Tehran, Iran',
    established: '2004',
    website: 'https://isa.ir',
    description:
      'Iran’s national agency for civilian space activities, operating indigenous Simorgh and Qaim launch systems and the Pars and Khayyam Earth observation satellites.',
    searchTerms: ['Iranian Space Agency', 'ISA Iran', 'Iran space', 'Khayyam satellite', 'Simorgh rocket', 'Pars satellite'],
    keyMissions: ['Khayyam Earth Observation Satellite', 'Pars-1 Remote Sensing Satellite', 'Simorgh Launch Vehicle'],
  },
  {
    slug: 'ssa-saudi',
    acronym: 'Saudi Space Agency',
    name: 'Saudi Space Agency (وكالة الفضاء السعودية)',
    country: 'Saudi Arabia',
    region: 'Asia',
    flag: '🇸🇦',
    headquarters: 'Riyadh, Saudi Arabia',
    established: '2018',
    website: 'https://ssa.gov.sa',
    description:
      'Directs the Kingdom’s Vision 2030 space ambitions, including human spaceflight to the ISS (Rayyanah Barnawi, Ali AlQarni), Artemis Accords participation, and deep space research.',
    searchTerms: ['Saudi Space Agency', 'SSA Saudi', 'Saudi space', 'Rayyanah Barnawi', 'Ali AlQarni', 'Vision 2030 space'],
    keyMissions: ['Axiom-2 Saudi Astronaut Mission to ISS', 'Artemis Accords Lunar Partnerships', 'Space Debris Monitoring'],
  },
  {
    slug: 'uaesa',
    acronym: 'UAESA',
    name: 'United Arab Emirates Space Agency',
    country: 'United Arab Emirates',
    region: 'Asia',
    flag: '🇦🇪',
    headquarters: 'Abu Dhabi, UAE',
    established: '2014',
    website: 'https://space.gov.ae',
    description:
      'UAE’s visionary space agency behind the Hope Probe (Emirates Mars Mission), Rashid lunar rovers, the upcoming Asteroid Belt Explorer (EMA), and astronaut Sultan Al Neyadi’s historic ISS expedition.',
    searchTerms: ['UAE Space Agency', 'UAESA', 'Hope Probe', 'Emirates Mars Mission', 'Rashid Rover', 'Sultan Al Neyadi', 'EMA Asteroid'],
    keyMissions: ['Hope Probe (Emirates Mars Mission)', 'Emirates Mission to the Asteroid Belt (EMA)', 'MBR Space Centre Lunar Rovers'],
  },
  {
    slug: 'msa-mongolia',
    acronym: 'Mongolian Space Agency',
    name: 'Mongolian Space Agency & Communications Authority',
    country: 'Mongolia',
    region: 'Asia',
    flag: '🇲🇳',
    headquarters: 'Ulaanbaatar, Mongolia',
    established: '2022',
    website: '',
    description:
      'Mongolia’s state body for aerospace development, operating Mazaalai cubesats, high-latitude space situational awareness, and the National Satellite Communications Project.',
    searchTerms: ['Mongolian Space Agency', 'Mongolia space', 'Mazaalai satellite', 'Ulaanbaatar space'],
    keyMissions: ['National High-Throughput Satellite', 'Mazaalai CubeSat Education Series', 'Steppe Space Science Program'],
  },
  {
    slug: 'kazcosmos',
    acronym: 'Kazcosmos',
    name: 'Kazakhstan National Space Agency (Kazcosmos)',
    country: 'Kazakhstan',
    region: 'Asia',
    flag: '🇰🇿',
    headquarters: 'Astana, Kazakhstan',
    established: '2007',
    website: 'https://gharysh.kz',
    description:
      'The National Space Agency of Kazakhstan, home to the historic Baikonur Cosmodrome, operating KazSat communications and KazEOSat Earth observation satellites.',
    searchTerms: ['Kazcosmos', 'Kazakhstan space', 'Baikonur', 'KazSat', 'KazEOSat'],
    keyMissions: ['Baiterek Green Rocket Complex at Baikonur', 'KazEOSat Earth Observation Constellation', 'KazSat-3 Telecom'],
  },

  // -------------------------------------------------------------
  // AFRICA
  // -------------------------------------------------------------
  {
    slug: 'sansa',
    acronym: 'SANSA',
    name: 'South African National Space Agency',
    country: 'South Africa',
    region: 'Africa',
    flag: '🇿🇦',
    headquarters: 'Pretoria & Hermanus, South Africa',
    established: '2010',
    website: 'https://www.sansa.org.za',
    description:
      'South Africa’s space agency managing the Hermanus Space Weather Regional Warning Centre, deep-space telemetry at Hartebeesthoek (supporting Artemis), and Earth observation satellites.',
    searchTerms: ['South African National Space Agency', 'SANSA', 'South Africa space', 'Hartebeesthoek', 'Space Weather Hermanus'],
    keyMissions: ['Deep Space Ground Tracking for Artemis', 'Hermanus Space Weather Warning Centre', 'ZACube Series'],
  },
  {
    slug: 'egsa',
    acronym: 'EgSA',
    name: 'Egyptian Space Agency',
    country: 'Egypt',
    region: 'Africa',
    flag: '🇪🇬',
    headquarters: 'Cairo (Space City), Egypt',
    established: '2018',
    website: 'https://egsa.gov.eg',
    description:
      'Hosts the African Space Agency (AfSA) headquarters in Space City, Cairo; operates EgyptSat-A and MisrSat-2 remote sensing satellites, and advances satellite testing infrastructure.',
    searchTerms: ['Egyptian Space Agency', 'EgSA', 'Egypt space', 'MisrSat-2', 'African Space Agency Cairo'],
    keyMissions: ['MisrSat-2 Optical Imaging Satellite', 'African Space Agency (AfSA) Headquarters', 'NExSat-1 Technology Demonstration'],
  },
  {
    slug: 'nasrda',
    acronym: 'NASRDA',
    name: 'National Space Research and Development Agency',
    country: 'Nigeria',
    region: 'Africa',
    flag: '🇳🇬',
    headquarters: 'Abuja, Nigeria',
    established: '1999',
    website: 'https://nasrda.gov.ng',
    description:
      'Nigeria’s principal space research agency operating NigeriaSat Earth observation satellites and NigComSat communications satellites, with focus on food security and resource management.',
    searchTerms: ['NASRDA', 'Nigeria space', 'NigeriaSat', 'NigComSat', 'Abuja space agency'],
    keyMissions: ['NigeriaSat-2 and NigeriaSat-X', 'NigComSat-1R Communications', 'African Regional Centre for Space Science'],
  },
  {
    slug: 'esti-ethiopia',
    acronym: 'SSGI / ESTI',
    name: 'Space Science and Geospatial Institute (formerly ESTI)',
    country: 'Ethiopia',
    region: 'Africa',
    flag: '🇪🇹',
    headquarters: 'Addis Ababa, Ethiopia',
    established: '2016',
    website: 'https://ssgi.gov.et',
    description:
      'Ethiopia’s space and geospatial institute operating ETRSS-1 optical satellites, Entoto Observatory, and astronomical research in East Africa.',
    searchTerms: ['Space Science and Geospatial Institute', 'ESTI', 'SSGI', 'Ethiopia space', 'ETRSS-1', 'Entoto Observatory'],
    keyMissions: ['ETRSS-1 Earth Remote Sensing Satellite', 'Entoto Observatory and Research Center', 'East Africa Space Node'],
  },
  {
    slug: 'asal-algeria',
    acronym: 'ASAL',
    name: 'Algerian Space Agency (Agence Spatiale Algérienne)',
    country: 'Algeria',
    region: 'Africa',
    flag: '🇩🇿',
    headquarters: 'Algiers, Algeria',
    established: '2002',
    website: 'https://www.asal.dz',
    description:
      'Algeria’s space agency overseeing the Alsat Earth observation constellation (Alsat-1B, Alsat-2A/B) and Alcomsat-1 communications satellite for North Africa.',
    searchTerms: ['Algerian Space Agency', 'ASAL', 'Algeria space', 'Alsat', 'Alcomsat-1'],
    keyMissions: ['Alsat-2 High-Resolution Optical Fleet', 'Alcomsat-1 Telecommunications', 'National Space Program 2040'],
  },
  {
    slug: 'ksa-kenya',
    acronym: 'Kenya Space Agency',
    name: 'Kenya Space Agency',
    country: 'Kenya',
    region: 'Africa',
    flag: '🇰🇪',
    headquarters: 'Nairobi, Kenya',
    established: '2017',
    website: 'https://ksa.go.ke',
    description:
      'Coordinates Kenyan space activities, the historic Luigi Broglio Space Center (San Marco platform) in Malindi, and the Taifa-1 operational Earth observation satellite.',
    searchTerms: ['Kenya Space Agency', 'KSA Kenya', 'Kenya space', 'Taifa-1', 'Malindi spaceport'],
    keyMissions: ['Taifa-1 Optical Earth Observation Satellite', 'Luigi Broglio Space Center (Malindi)', 'National Space Strategy 2030'],
  },
  {
    slug: 'rsa-rwanda',
    acronym: 'Rwanda Space Agency',
    name: 'Rwanda Space Agency (RSA)',
    country: 'Rwanda',
    region: 'Africa',
    flag: '🇷🇼',
    headquarters: 'Kigali, Rwanda',
    established: '2021',
    website: 'https://space.gov.rw',
    description:
      'Africa’s fast-rising space authority pioneering satellite mega-constellation filings (Cinnamon), geospatial data hubs, and the Artemis Accords partnership.',
    searchTerms: ['Rwanda Space Agency', 'RSA Rwanda', 'Rwanda space', 'Rwasat-1', 'Kigali space'],
    keyMissions: ['National GeoHub Analytics Platform', 'Artemis Accords Africa Signatory', 'RwaSat Micro-satellite Series'],
  },
  {
    slug: 'crts-morocco',
    acronym: 'CRTS',
    name: 'Royal Centre for Remote Sensing (Centre Royal de Télédétection Spatiale)',
    country: 'Morocco',
    region: 'Africa',
    flag: '🇲🇦',
    headquarters: 'Rabat, Morocco',
    established: '1989',
    website: 'http://www.crts.gov.ma',
    description:
      'Morocco’s national remote sensing authority managing the Mohammed VI-A and Mohammed VI-B high-resolution optical Earth reconnaissance satellites.',
    searchTerms: ['Royal Centre for Remote Sensing', 'CRTS', 'Morocco space', 'Mohammed VI satellite'],
    keyMissions: ['Mohammed VI-A and VI-B Reconnaissance Constellation', 'Mediterranean & Saharan Space Remote Sensing'],
  },

  // -------------------------------------------------------------
  // OCEANIA
  // -------------------------------------------------------------
  {
    slug: 'australian-space-agency',
    acronym: 'Australian Space Agency',
    name: 'Australian Space Agency (ASA)',
    country: 'Australia',
    region: 'Oceania',
    flag: '🇦🇺',
    headquarters: 'Adelaide, South Australia',
    established: '2018',
    website: 'https://www.space.gov.au',
    description:
      'Australia’s national space agency leading the "Roo-ver" semi-autonomous lunar rover for NASA’s Artemis missions, space situational awareness in the Southern Hemisphere, and regional spaceports.',
    searchTerms: ['Australian Space Agency', 'ASA Australia', 'Australia space', 'Roo-ver', 'Grose rover', 'Kanyini', 'Adelaide space'],
    keyMissions: ['Roo-ver Australian Lunar Rover for Artemis', 'Kanyini Earth Observation Satellite', 'Southern Space Launch Facilities'],
  },
  {
    slug: 'new-zealand-space-agency',
    acronym: 'New Zealand Space Agency',
    name: 'New Zealand Space Agency (NZSA)',
    country: 'New Zealand',
    region: 'Oceania',
    flag: '🇳🇿',
    headquarters: 'Wellington, New Zealand',
    established: '2016',
    website: 'https://www.mbie.govt.nz/science-and-technology/space',
    description:
      'Regulates and promotes New Zealand’s thriving commercial launch industry centered around Rocket Lab’s Launch Complex 1 on the Māhia Peninsula, and leads the MethaneSAT climate satellite operations.',
    searchTerms: ['New Zealand Space Agency', 'NZSA', 'New Zealand space', 'Mahia Peninsula', 'Rocket Lab New Zealand', 'MethaneSAT'],
    keyMissions: ['MethaneSAT Mission Operations Control', 'Māhia Peninsula Orbital Spaceport Regulation', 'Artemis Accords Collaboration'],
  },
]

export const REGIONS: Region[] = [
  'North America',
  'South America',
  'Europe',
  'Asia',
  'Africa',
  'Oceania',
]

export function getAllAgencies(): SpaceAgency[] {
  return SPACE_AGENCIES
}

export function getAgencyBySlug(slug: string): SpaceAgency | undefined {
  const normalized = (slug || '').toLowerCase().trim()
  return SPACE_AGENCIES.find(
    (a) => a.slug.toLowerCase() === normalized || a.acronym.toLowerCase() === normalized
  )
}

export function getAgenciesByRegion(region: Region): SpaceAgency[] {
  return SPACE_AGENCIES.filter((a) => a.region === region)
}
